.github/workflows/release.yml
https://scalar-labs.atlassian.net/browse/DLT-9382
When executing release workflow, it fails because it is trying to upload unchanged charts.
```
Looking up latest tag...
Discovering changed charts since 'scalardl-1.2.3'...
Installing chart-releaser...
Adding cr directory to PATH...
Packaging chart 'charts/scalardl'...
Successfully packaged chart in /home/runner/work/helm-charts/helm-charts/charts/scalardl and saved it to: .cr-release-packages/scalardl-1.2.3.tgz
Packaging chart 'charts/schema-loading'...
Successfully packaged chart in /home/runner/work/helm-charts/helm-charts/charts/schema-loading and saved it to: .cr-release-packages/schema-loading-1.3.1.tgz
Releasing charts...
Error: error creating GitHub release: POST https://api.github.com/repos/scalar-labs/helm-charts/releases: 422 …
```
=> Fix to skip existing in release flow

charts/scalardl/Chart.yaml, charts/scalardl/README.md, charts/scalardl/values.yaml
[v1.1.0](https://github.com/scalar-labs/scalar-envoy/releases/tag/v1.1.0) released for `scalar-envoy`.
Image:
https://github.com/orgs/scalar-labs/packages/container/scalar-envoy/6459590?tag=1.1.0
=> Update scalar-envoy to 1.1.0

charts/schema-loading/README.md, charts/schema-loading/templates/batchjob-schema-loading.yaml, charts/schema-loading/values.yaml
Updated the following:
* Make it able to specify `cassandraReplicationStrategy`
* Make the default replication strategy Simple to make it runnable without custom configs. (NetworkTopology with replication factor 1 will fail in C*)
* Make it able to specify `schemaType` to create Auditor schema.
See [another PR](https://github.com/scalar-labs/scalar-kubernetes/pull/142) for the custom config.
=> Update to make it runnable without custom config and make auditor work

charts/scalardb/files/scalardb_grafana_dashboard.json, charts/scalardb/templates/scalardb/servicemonitor.yaml, charts/scalardl-audit/README.md, charts/scalardl-audit/files/envoy_grafana_dashboard.json, charts/scalardl-audit/files/scalardl-audit_grafana_dashboard.json, charts/scalardl-audit/templates/auditor/deployment.yaml, charts/scalardl-audit/templates/auditor/service.yaml, charts/scalardl-audit/templates/auditor/servicemonitor.yaml, charts/scalardl-audit/values.yaml, charts/scalardl/README.md, charts/scalardl/files/envoy_grafana_dashboard.json, charts/scalardl/files/scalardl_grafana_dashboard.json, charts/scalardl/templates/ledger/deployment.yaml, charts/scalardl/templates/ledger/service.yaml, charts/scalardl/templates/ledger/servicemonitor.yaml, charts/scalardl/values.yaml
- Fixed the dashboard because the `scalardb` metrics name changed.
- Changed datasource name to `Prometheus`.
- Add and fix missing manifest for metrics.
- https://github.com/scalar-labs/scalardb/pull/274
=> Update scalardb, scalardl and scalardl-audit chart for grafana

index.yaml
- update index.yaml for envoy charts
- If I use the release workflow of 'github-actions', `scalardb-charts` and `scalar-audit-charts` will also be released, so this time I manually released envoy-charts first. https://github.com/scalar-labs/helm-charts/releases/tag/envoy-1.0.0
```
cr index
```
- Check the checksum.
```
curl -L https://github.com/scalar-labs/helm-charts/releases/download/envoy-1.0.0/envoy-1.0.0.tgz | sha256sum
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   623  100   623    0     0   1117      0 --:--:-- --:--:-- --:--:--  1116
100  7696  100  7696    0     0   7760      0 --:--:-- --:--:-- --:--:--  7760
1c8b4801539faef21bafa40ae01210562df0f911b07636042dbf5a9d44558dd3  -
```
```
digest: …
```
=> Update index.yaml for envoy-charts

charts/envoy/templates/prometheusrules.yaml, charts/envoy/templates/servicemonitor.yaml
This PR fixes to add common labels to PrometheusRule and ServiceMonitor CRs in envoy chart.
```diff
--- /tmp/main.yaml      2021-09-20 15:41:08.615481407 +0900
+++ /tmp/envoy-prometheus-operator-labels.yaml  2021-09-20 15:41:27.523784820 +0900
@@ -124,10 +124,14 @@
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
-  labels:
-    app: prometheus-operator
-    release: prometheus
name: RELEASE-NAME-envoy-envoy-prometheus-alerts-rules
+  labels:
+    helm.sh/chart: envoy-1.0.0
+    app.kubernetes.io/name: envoy
+    app.kubernetes.io/instance: RELEASE-NAME
+    app.kubernetes.io/app: envoy
+    app.kubernetes.io/version: "1.1.0"
+    app.kubernetes.io/managed-by: Helm
namespace: monitoring
spec:
groups:
@@ -178,6 +182,13 @@
kind: ServiceMonitor
metadata:
name: …
```
=> envoy: Fix to add common labels to prometheus-operator CRs

charts/scalardl/Chart.yaml, charts/scalardl/README.md
- This is the corresponding version of `scalardl charts` with `envoy` charts applied. (major version release)
- The `scalardb charts` and `scalardl-audit charts` are not yet released and will be released with the `scalardl charts` upgrade.
=> Bump up Scalar DL version to 3.0.0

charts/schema-loading/Chart.yaml, charts/schema-loading/README.md, charts/schema-loading/values.yaml
* This is a PR to bump up the schema loading version.
* `Only the schema loading version` will be released
=> Bump up schema loading version to 2.1.0

index.yaml
- Only Schema loading Charts will be sync in the index yaml.
```
$ curl -L https://github.com/scalar-labs/helm-charts/releases/download/schema-loading-2.1.0/schema-loading-2.1.0.tgz | sha256sum
acefc50780952e14fa7c13ee8e2cf52a12230cc315e608f579e2b5dae89dd2b3
```
=> Modify index yaml from helm repo

index.yaml
- sync index yaml(cr index command)
- `scalardl`, `scalardl-audit`, and `scalardb` charts have been added to the index yaml.
- The reason why I didn't run it with github actions is that github actions targets the prior commit contents, so it didn't deploy when I ran it, so I had to run the chart releaser manually..
```
$ cr package charts/scalardl
$ cr package charts/scalardb
$ cr package charts/scalardl-audit
$ cr upload --skip-existing
$ cr index --charts-repo https://scalar-labs.github.io/helm-charts --index-path index.yaml
```
=> Modify index yaml

charts/envoy/Chart.yaml, charts/envoy/README.md, charts/envoy/templates/deployment.yaml, charts/envoy/values.yaml
- bump up scalar-envoy version to 1.2.0 (https://github.com/orgs/scalar-labs/packages/container/scalar-envoy/8462600?tag=1.2.0)
- add serviceListeners environment
``` yaml
envoyConfiguration:
serviceListeners: ledger-service:40051,ledger-privileged:40052
```
* Envoy SDS API
``` sh
curl http://0.0.0.0:9001/listeners?format=json
{
"listener_statuses": [
{
"name": "ledger-service",
"local_address": {
"socket_address": {
"address": "0.0.0.0",
"port_value": 40051
}
}
},
{
"name": "ledger-privileged",
"local_address": {
"socket_address": {
"address": "0.0.0.0",
"port_value": 40052
}
}
}
]
}
```
=> Bump up scalar-envoy version to 1.2.0 for envoy charts

charts/scalardb/Chart.yaml, charts/scalardb/README.md, charts/scalardb/values.yaml
- Now that the patch version(3.3.1) of scalardb has been upgraded, update the patch version(1.2.1) of the helm charts in scalardb.
=> Bump up scalardb charts patch version to 1.2.1

charts/scalardl-audit/Chart.yaml, charts/scalardl-audit/README.md, charts/scalardl-audit/values.yaml, charts/scalardl/Chart.yaml, charts/scalardl/README.md, charts/scalardl/values.yaml
- Now that the patch version(3.2.1) of scalardl and scalardl audit has been upgraded, update the patch version(3.2.1, 1.2.1) of the helm charts in scalardl and scalardl-audit.
=> Bumpup scalardl and scalardl audit application patch version to 3.2.1

charts/scalardl-audit/Chart.yaml, charts/scalardl-audit/README.md, charts/scalardl-audit/values.yaml, charts/scalardl/Chart.yaml, charts/scalardl/README.md, charts/scalardl/values.yaml
Now that the patch version(3.3.0) of scalardl and scalardl audit has been upgraded, update the patch version(3.3.0, 1.3.0) of the helm charts in scalardl and scalardl-audit.
=> Bumpup scalardl and scalardl audit application minor version to 3.3.0

charts/scalardb/Chart.yaml, charts/scalardb/README.md, charts/scalardb/values.yaml
* Now that the patch version(3.4.0) of scalardb has been upgraded, update the patch version(1.3.0) of the helm charts in scalardb.
=> Bumpup scalardb charts minor version to 1.3.0

charts/envoy/Chart.yaml, charts/envoy/README.md, charts/envoy/templates/deployment.yaml, charts/envoy/templates/podsecuritypolicy.yaml, charts/envoy/templates/psp-clusterrole.yaml, charts/envoy/templates/psp-clusterrolebinding.yaml, charts/envoy/templates/serviceaccount.yaml, charts/envoy/values.yaml
- We used [kubeauidt](https://github.com/Shopify/kubeaudit) to conducted a security audit in envoy charts.
- I fixed the items pointed out in the security audit.
- I created pod security policy to envoy charts
- The reason for creating the `pod security policy` is to avoid violating the settings that comply with the security audit log.
``` sh
$ kubeaudit all -k kube-audit.yaml -f <(helm template scalr-envoy charts/envoy) -m error
-- [error] AutomountServiceAccountTokenTrueAndDefaultSA
Message: Default service account with token mounted. automountServiceAccountToken should be set to 'false' on either the ServiceAccount or on the PodSpec or a non-default service account should be used.
-- [error] CapabilityOrSecurityContextMissing
Message: Security Context not set. The Security Context …
```
=> Fixed the items pointed out in the security audit in envoy charts

charts/scalardb/Chart.lock, charts/scalardb/Chart.yaml, charts/scalardb/README.md, charts/scalardl-audit/Chart.lock, charts/scalardl-audit/Chart.yaml, charts/scalardl-audit/README.md, charts/scalardl/Chart.lock, charts/scalardl/Chart.yaml, charts/scalardl/README.md
- Now that the major version(2.0.0) of envoy charts has been upgraded, update the major version of the helm charts in scalardl(4.0.0), scalardl-audit(2.0.0) and scalardb(2.0.0).
- Upgraded envoy charts PR
- https://github.com/scalar-labs/helm-charts/pull/49
=> Bumpup major version of each `charts` with the upgrade of `envoy-charts`.

.github/workflows/helm_charts_scalar.yml
- Since EKS and AKS support 1.21, we have added the corresponding k8s version 1.21.
- The reason why it is 1.21.2 is that the latest version of the image of `kindest:node` is `1.21.2
- https://hub.docker.com/r/kindest/node/tags?page=1&name=1.21
=> Add k8s support version for CI

charts/scalardb/Chart.yaml, charts/scalardb/README.md, charts/scalardb/values.yaml
- Now that the patch version(3.4.1) of scalardb server has been upgraded, update the patch version of the helm charts in scalardb(2.0.1)
=> Bump up scalardb patch version to 3.4.1

charts/scalardl-audit/Chart.yaml, charts/scalardl-audit/README.md, charts/scalardl-audit/values.yaml, charts/scalardl/Chart.yaml, charts/scalardl/README.md, charts/scalardl/values.yaml
- Now that the patch version(3.3.1) of scalar-ledger and scalar-auditor has been upgraded, update the patch version of the helm charts in scalardl(4.0.1) and scalardl-audit(2.0.1)
=> Bumpup scalardl patch version to 3.3.1

.github/kube-audit.yaml, .github/workflows/helm_charts_scalar.yml
- Set `kubeaudit` to CI to do security audit for each helm chart
=> Add kubeaudit workflow to CI

charts/schema-loading/Chart.yaml, charts/schema-loading/README.md, charts/schema-loading/values.yaml
- Now that the minor version(3.2.0) of scalardl schema loader has been upgraded, update the patch version of the helm charts in scalardl shcema loader minor version(2.2.0)
=> Bumpup scalardl schema loader minor version to 2.2.0

charts/schema-loading/Chart.yaml, charts/schema-loading/README.md, charts/schema-loading/values.yaml
- Now that the minor version(3.3.0) of scalardl schema loader has been upgraded, update the patch version of the helm charts in scalardl shcema loader minor version(2.3.0)
=> Bumpup scalardl schema loader minor version to 2.3.0

charts/scalardb/files/grafana/scalardb_grafana_dashboard.json
- Added graphs for `two phase commit` related metrics to `scalardb grafana dashboard`.
- scalardb_stats_two_phase_commit_transaction_get_state
- scalardb_stats_two_phase_commit_transaction_abort
- scalardb_stats_two_phase_commit_transaction_transaction_start
- scalardb_stats_two_phase_commit_transaction_transaction_join
- scalardb_stats_two_phase_commit_transaction_transaction_get
- scalardb_stats_two_phase_commit_transaction_transaction_scan
- scalardb_stats_two_phase_commit_transaction_transaction_mutate
- scalardb_stats_two_phase_commit_transaction_transaction_prepare
- scalardb_stats_two_phase_commit_transaction_transaction_validate
- scalardb_stats_two_phase_commit_transaction_transaction_commit
- scalardb_stats_two_phase_commit_transaction_transaction_rollback
=> Modify scalardb grafana dashboard related to `two phase commit`

.github/workflows/helm_charts_scalar.yml, charts/envoy/values.schema.json, charts/scalardb/values.schema.json, charts/scalardl-audit/values.schema.json, charts/scalardl/values.schema.json, charts/schema-loading/values.schema.json, scripts/update-values-schema-json.sh, scripts/update-values-schema-json/Dockerfile, scripts/verify-chart-docs.sh, scripts/verify-files.sh, scripts/verify-values-schema-json.sh
* Add values.schema.json to each helm charts.
* `values.schema.json` can be used to provide more robust Helm input validation, with the additional benefit of enforcing value restrictions from a single schema file.
```
$ helm plugin install https://github.com/karuppiah7890/helm-schema-gen.git
$ helm schema-gen charts/${chart_name}/values.yaml > values.schema.json
```
=> Add `values.schema.json` and verify values.schema.json

.github/workflows/helm_charts_scalar.yml, charts/scalardb/README.md, charts/scalardb/templates/scalardb/deployment.yaml, charts/scalardb/templates/scalardb/podsecuritypolicy.yaml, charts/scalardb/templates/scalardb/psp-clusterrole.yaml, charts/scalardb/templates/scalardb/serviceaccount.yaml, charts/scalardb/values.yaml
- We used [kubeaudit](https://github.com/Shopify/kubeaudit) to conducted a security audit in scalardb charts.
- I fixed the items pointed out in the security audit.
- I created pod security policy to scalardb charts
- The reason for creating the `pod security policy` is to avoid violating the settings that comply with the security audit log.
``` sh
$ kubeaudit all -k .github/kube-audit.yaml -f <(helm template --generate-name "charts/scalardb") -m error
-- [error] AutomountServiceAccountTokenTrueAndDefaultSA
Message: Default service account with token mounted. automountServiceAccountToken should be set to 'false' on either the ServiceAccount or on the PodSpec or a non-default service account should be used.
-- [error] CapabilityOrSecurityContextMissing
Message: Security Context not set. …
```
=> Fixed the items pointed out in the security audit in scalardb charts

scripts/update-values-schema-json.sh, scripts/update-values-schema-json/Dockerfile
- The repository of helm-schema-gen is in maintenance mode, so fork the repository and change to use the fork destination.
- https://github.com/scalar-labs/helm-schema-gen
=> Change the github repository of helm-schema-gen

charts/schema-loading/templates/batchjob-schema-loading.yaml
Remove `-u` option from scalar schema-loading helm chart for Cosmos DB.
**Issue**
```
[main] WARN com.scalar.db.schemaloader.SchemaLoader - Storage-specific options (--cassandra, --cosmos, --dynamo, --jdbc) are deprecated and will be removed in the future. Please use the --config option along with your config file instead.
Unknown options: '-u', 'cassandra'
Usage: java -jar scalardb-schema-loader-<version>.jar --cosmos [-D]
[--no-scaling] -f=<schemaFile> -h=<uri> -p=<key> [-r=<ru>]
Create/Delete Cosmos DB schemas
-D, --delete-all       Delete tables
-f, --schema-file=<schemaFile>
Path to the schema json file
-h, --host=<uri>       Cosmos DB account URI
--no-scaling       Disable auto-scaling for Cosmos DB
-p, --password=<key>   Cosmos DB key
-r, --ru=<ru>          Base resource unit
```
=> Update schema-loading helm chart for Cosmos DB

charts/scalardb/README.md, charts/scalardb/values.schema.json, charts/scalardb/values.yaml, charts/scalardl-audit/README.md, charts/scalardl-audit/values.schema.json, charts/scalardl-audit/values.yaml, charts/scalardl/README.md, charts/scalardl/values.schema.json, charts/scalardl/values.yaml, charts/schema-loading/README.md, charts/schema-loading/values.schema.json, charts/schema-loading/values.yaml
- The type of `values.schema.json` was set to `null` in some places, so this has been fixed.
- `values.yaml` should not be set to `null` as default value
- As for the conditional judgment of `helm`, if it is `null` or `empty character`, it will be `false`, so there is no need to change the logic of template.
- The version that applies `values.schema.json` has not been released yet, so it will not affect existing versions.
=> Fix the `values.schema.json` type being `null` 

charts/schema-loading/Chart.yaml, charts/schema-loading/values.yaml
- bump up schema loading to 3.2.1
- Create a branch (prepare-release-v*) from the tag where the `3.2.0` app version is released, and issue a PR against that branch.
```
helm search repo scalar-labs/schema-loading --versions
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
scalar-labs/schema-loading      2.4.0           3.3.0           A schema loading tool for Scalar DL.
scalar-labs/schema-loading      2.3.0           3.3.0           A schema loading tool for Scalar DL.
scalar-labs/schema-loading      2.2.0           3.2.0           A schema loading tool for Scalar DL.
scalar-labs/schema-loading      2.1.0           3.1.0           A schema loading tool for Scalar DL.
scalar-labs/schema-loading      1.3.0           1.3.0           Implementation schema loading …
```
=> Bump up schema loading to 3.2.1

charts/scalardl/Chart.yaml, charts/scalardl/README.md, charts/scalardl/values.yaml
I changed version of scalardl for release new version.
```
$ git checkout -b check-release-v4.1.1 refs/tags/scalardl-4.1.0
```
Could you please confirm the changes?
If there is no problem, I will create prepare-release-v4.1.1 branch in the same way, for release new version. Also, I will release each minor version of scalardl, and release scalardl-audit in the same way.
=> Check for bump up scalardl to v4.1.1

index.yaml
The entry of scalardl v3.0.1 removed by the following commit. (The following commit is related to scalardl-audit v1.0.1. At this time
we don't find the cause that this commit removes other chart's entry.)
b2a9e78995c8e2d4f99a58859b0a68d305acf84e
I the result of the above behavior, we cannot find chart "scalardl v3.0.1" in the helm search repo command.
So, we need to add entry of "scalardl v3.0.1" into the index.yaml.
Usually, the entry of index.yaml added by chart releaser automatically.
However, to fix the above issue, add entry of scalardl v3.0.1 manually in this commit.
=> Add scalardl v3.0.1 entry to index.yaml

README.md
If we want to see all versions of helm charts, we need to specify the `--versions` option in the `helm search repo` command. 
So, I added it in the README. Please take a look!
=> Add --versions option of helm search repo command in the README

charts/scalardb/files/grafana/scalardb_grafana_dashboard.json
This PR includes the following fixes of Grafana Dashboard of Scalar DB. Please take a look!
* Remove `service_` from some metrics name.
* About the following two metrics, rename `service_` to `transaction_`.
* Abort count
* Before : `scalardb_stats_distributed_transaction_service_abort_count`
* After  : `scalardb_stats_distributed_transaction_transaction_abort_count`
* Abort
* Before : `scalardb_stats_distributed_transaction_service_abort`
* After  : `scalardb_stats_distributed_transaction_transaction_abort`
* "Total" row includes requests rate of success and failure. So, it seems that the "Total Requests Rate" is better.
* "Total" -> "Total Requests Rate"
* It seems that the "Distributed Transaction" is better.
* "Distributed Storage Transaction Service" -> "Distributed Transaction …
=> Fix Scalar DB's Grafana Dashboard

charts/envoy/templates/deployment.yaml, charts/envoy/templates/service.yaml, charts/envoy/templates/serviceaccount.yaml, charts/scalardb/templates/scalardb/configmap.yaml, charts/scalardb/templates/scalardb/deployment.yaml, charts/scalardb/templates/scalardb/service.yaml, charts/scalardb/templates/scalardb/serviceaccount.yaml, charts/scalardl-audit/templates/auditor/deployment.yaml, charts/scalardl-audit/templates/auditor/secret.yaml, charts/scalardl-audit/templates/auditor/service.yaml, charts/scalardl/templates/ledger/deployment.yaml, charts/scalardl/templates/ledger/secret.yaml, charts/scalardl/templates/ledger/service.yaml, charts/schema-loading/templates/batchjob-schema-loading.yaml, charts/schema-loading/templates/secret.yaml
This PR allows `--namespace` flag to work when using `helm template` command to generate manifests.
Currently, `--namespace` flag works when installing a Helm chart with `helm install` command. However, when using `--namespace` flag with `helm template` command, namespace must be templated with `{{ .Release.Namespace }}` to specify namespace.
Users may use `helm template` command to generate a manifest file, and then apply that manifest file to the cluster using another tool.
You can verify that this change allows `--namespace` flag to work with `helm template` command by following the steps:
```
$ git checkout main
$ git show -q
commit 717daeeda7eea7a6e9e03404ce811b71e52ec346 (HEAD -> main, origin/main, origin/HEAD)
Author: kota2and3kan <kota2and3kan@users.noreply.github.com>
Date:   Tue …
```
=> Make namespace configurable in helm template

charts/scalardl-audit/files/grafana/scalardl_audit_grafana_dashboard.json, charts/scalardl/files/grafana/scalardl_grafana_dashboard.json
This PR update the Graph Title of Grafana Dashboard.  
There are two kind of changes.
Both fixes are related to https://github.com/scalar-labs/helm-charts/pull/81. (I fixed each graph title to consistency of Grafana Dashboard between Scalar DB and Scalar DL.)  
1. `XXX Request Count` -> `XXX Request Per One Second`
2. `XXX Request` -> `XXX Request Execution Time (percentile)`
One is update `Count` -> `Per One Second`, because the irate() function of prometheus returns metrics that request number of per one second.  
Please see the following PR commnet for details of irate() function.  
* Reference information
* https://github.com/scalar-labs/helm-charts/pull/81#issuecomment-1066435328
Next one is `Request` -> `Request Execution Time (percentile)`, because the metrics show execution time …
=> Fix graph title of Scalar DL's Grafana Dashboard

docs/conf/scalar-prometheus-custom-values.yaml, docs/getting-started-monitoring.md
This PR add the getting started guide with helm charts of the monitoring.
There are two files.
* docs/conf/scalar-prometheus-custom-values.yaml
* This is a minimum custom value file of `kube-prometheus-stack` for monitoring Scalar products.
* I have created this file based on the following file.
* https://github.com/superbrothers/helm-charts/blob/monitoring/charts/monitoring/values.yaml
* docs/getting-started-monitoring.md
* This guide deploys Prometheus Operator (kube-prometheus-stack) on the minikube for testing.
* Also, this guide describes the setting that we need to enable monitoring of each Scalar product.
Also, there are some redundancy between this guide and `Getting Started with Helm Charts (Scalar DB/DL)`.   
I will separate the redundancy point in the another PR after each …
=> Add Getting Started Guide with Helm Chart (Monitoring)

docs/getting-started-monitoring.md
In this PR, I added the `-n monitoring` flag to `helm uninstall` command.
In the Getting Started Guide with Monitoring (Prometheus Operator), we deploy kube-prometheus-stack into the `monitoring` namespace. So, we need to specify the namespace `monitoring`, when we delete it.
If we don't specify it, the `helm uninstall` command returns error.
* Without `-n monitoring`
```console
$ helm uninstall scalar-monitoring
Error: uninstall: Release not loaded: scalar-monitoring: release: not found
```
* With `-n monitoring`
```console
$ helm uninstall scalar-monitoring -n monitoring
release "scalar-monitoring" uninstalled
```
=> Add `-n monitoring` flag to `helm uninstall` command

docs/getting-started-scalardl-auditor.md, docs/getting-started-scalardl-ledger.md
This PR add the getting started guide with helm charts of Scalar DL.
There are two documents.
* Getting Started with Helm Charts (Scalar DL Ledger)
* Create Ledger environment on the minikube.
* Getting Started with Helm Charts (Scalar DL Auditor)
* Add the Auditor environment on the same minikube as Ledger.
* The minikube is same, but I use two Cassandra (for Ledger and Auditor).
I created this document with priority on reproducibility in user's environment.  
So, I describe concrete commands in all steps.  
Also, to avoid issues depending on each environment as much as possible, this guide runs all component (include the client that runs Scalar DL sample contract) as docker container.  
Also, there are some redundancy in the `Run Scalar DL sample contract` section between two document. …
=> Add Getting Started Guide with Helm Chart (Scalar DL)

docs/README.md, docs/getting-started-monitoring.md, docs/getting-started-scalar-helm-charts.md, docs/getting-started-scalardb.md, docs/getting-started-scalardl-auditor.md, docs/getting-started-scalardl-ledger.md
According to the following two comment in the another PR, this PR separates the redundancy part from Getting Started Guide with Helm Charts.
https://github.com/scalar-labs/helm-charts/pull/85#discussion_r852755807
https://github.com/scalar-labs/helm-charts/pull/85#discussion_r852756235
Also, I updated index of document to make uses reach each document properly via separated document.
Users can access each Getting Started Guide according to this index as follows.
```
+---> [Scalar DB Server]
|
+---> [Scalar DL Ledger]
|
[Start minikube (root doc)] ---+---> [Scalar DL Auditor]
|
+---> [Monitoring using Prometheus Operator]
|
+---> [Logging using Loki Stack]
```
=> Separates the redundancy part and Update index

charts/envoy/Chart.yaml, charts/envoy/README.md, charts/scalardb/Chart.lock, charts/scalardb/Chart.yaml, charts/scalardb/README.md, charts/scalardb/values.yaml, charts/scalardl-audit/Chart.lock, charts/scalardl-audit/Chart.yaml, charts/scalardl-audit/README.md, charts/scalardl-audit/values.yaml, charts/scalardl/Chart.lock, charts/scalardl/Chart.yaml, charts/scalardl/README.md, charts/scalardl/values.yaml, charts/schema-loading/Chart.yaml, charts/schema-loading/README.md, charts/schema-loading/values.yaml
This PR update version of each chart to keep main branch latest.
We need to update version in main branch when we release most recent version of Helm Charts to keep main branch latest, but I forgot it.
Sorry for overlooking this issue...
Also, we don't need to do any release operation because all latest charts are released correctly as follows.
```console
$ helm search repo scalar-labs
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
scalar-labs/envoy               2.0.1           1.2.0           Envoy Proxy for Scalar applications
scalar-labs/scalardb            2.2.4           3.5.2           Scalar DB server
scalar-labs/scalardl            4.2.1           3.4.0           Scalar DL is a tamper-evident and scalable dist...
scalar-labs/scalardl-audit      2.2.1 …
```
=> Update version of each chart to latest

docs/conf/scalar-prometheus-custom-values.yaml
This PR adds a configuration to the sample custom values of the "Getting Started Monitoring" guide to allow Grafana to be embedded in the other websites (mainly, for Scalar Manager by far).
=> Configure Grafana to allow the embedding feature

charts/scalardb/templates/scalardb/configmap.yaml, charts/scalardb/templates/scalardb/deployment.yaml, charts/scalardb/templates/scalardb/secret.yaml
This PR updates Scalar DB Helm Charts to use `Secret` resource for passing username/password to containers.
As a result of discussion, we decided to update Scalar DB Dockerfile and Helm Charts to the same as Scalar DL for keeping consistency among Scalar products and for improving maintainability.
So, I update Scalar DB Helm Charts based on the Scalar DL Helm Charts in this PR.
---
Note that we need to apply this update after releasing new version Scalar DB that includes the following PR.
* https://github.com/scalar-labs/scalardb/pull/590
So, we cannot test this Helm Charts now (CI does not work).
We can only test it in the local environment only.
For example, you can test this chart on minikube as follows.
* Create a docker image of Scalar DB Server that supports …
=> Use Secret resource for username and password in the Scalar DB chart

.github/workflows/helm_charts_scalar.yml
This PR removes Kubernetes v1.18 from the version list of the chart testing and the kubeval for the following reasons.
* Kubernetes v1.18 is no longer supported by both EKS and AKS.
* It is already stated that v1.18 is not supported by this repo. ([v1.19+ is required in the README](https://github.com/scalar-labs/helm-charts#prerequisites))
* Kubeval for Ingress resources with v1.18 resulted in an error due to a lack of the JSON schema file. https://github.com/scalar-labs/helm-charts/pull/89#issuecomment-1138297232
=> Remove chart testing for Kubernetes v1.18

charts/scalardb/README.md, charts/scalardb/templates/scalardb/deployment.yaml, charts/scalardb/values.yaml, charts/scalardl-audit/README.md, charts/scalardl-audit/templates/auditor/deployment.yaml, charts/scalardl-audit/values.yaml
This PR updates Scalar DB and Auditor charts to use default ports (Scalar DB -> 60051 / Auditor -> 40051, 40052).
=> Use default port in the chart of Scalar DB and Auditor

charts/scalardl/README.md, charts/scalardl/templates/ledger/configmap.yaml, charts/scalardl/templates/ledger/deployment.yaml, charts/scalardl/values.schema.json, charts/scalardl/values.yaml
This PR add a new feature that accepting user customized ledger.properties file in the Scalar DL Ledger Helm Charts.
By default, it is disabled.
---
You can use your customized ledger.properties by the following steps.
1. Set `ledger.useCustomizedConfiguration.enabled=true` in your custom value file.
1. Create a `ConfigMap` resource using your ledger.properties file as follows.
```console
kubectl create configmap ledger-customized-config --from-file=ledger.properties.tmpl=ledger.properties
```
1. Create schema using the Scalar DL Schema Loader Helm Chats.
1. Deploy Scalar DL using Helm Charts.
---
Also, you can use a `Secret` resource to pass the credentials as a environment variables as follows.
1. Set `ledger.useCustomizedConfiguration.useSecret=true` in your custom …
=> Support customized ledger.properties in Scalar DL Ledger

charts/scalardl-audit/README.md, charts/scalardl-audit/templates/auditor/configmap.yaml, charts/scalardl-audit/templates/auditor/deployment.yaml, charts/scalardl-audit/values.schema.json, charts/scalardl-audit/values.yaml
This PR add a new feature that accepting user customized auditor.properties file in the Scalar DL Auditor Helm Charts.
By default, it is disabled.
---
You can use your customized auditor.properties by the following steps.
1. Deploy Scalar DL Ledger.
1. Set `auditor.useCustomizedConfiguration.enabled=true` in your custom value file.
1. Create a `ConfigMap` resource using your auditor.properties file as follows.
```console
kubectl create configmap auditor-customized-config --from-file=auditor.properties.tmpl=auditor.properties
```
1. Create schema using the Scalar DL Schema Loader Helm Chats.
1. Deploy Scalar DL Auditor using Helm Charts.
---
Also, you can use a `Secret` resource to pass the credentials as a environment variables as follows.
1. Set …
=> Support customized auditor.properties in Scalar DL Auditor

index.yaml
This PR removes Scalar Manager Helm Chart from index to make it invisible from users in the `helm search` command.
---
When I updated the Scalar DB version of main branch to keep it latest in the following PR, there were some conflicts.
https://github.com/scalar-labs/helm-charts/pull/114
To resolve the above conflicts, I merged  main branch to prepare-release-v2.3.0 branch (This branch uses for release of Scalar DB).
In this merge operation merged Scalar Manager Helm Chart from main to prepare-release-v2.3.0.
As a result, the Chart Releaser in the release workflow detects Scalar Manager Helm Chart and released it.
This is an unexpected release...
The tag and asset of Scalar Manager v1.0.0 has already created by Chart Releaser.
However, I think we can make it invisible from users in the …
=> Remove Scalar Manager from index.yaml to make it invisible

charts/scalardl-audit/README.md, charts/scalardl-audit/values.schema.json, charts/scalardl-audit/values.yaml, charts/scalardl/README.md, charts/scalardl/values.schema.json, charts/scalardl/values.yaml
This PR adds the security context as default values in the Scalar DL (Ledger/Auditor) Helm Charts.
After this updates, the Pod (Deployment) includes the following security context by default.
```json
$ kubectl get deployment scalardl-ledger-ledger -o jsonpath='{.spec.template.spec.containers[].securityContext}' | jq .
{
"allowPrivilegeEscalation": false,
"capabilities": {
"drop": [
"ALL"
]
},
"runAsNonRoot": true
}
```
```json
$ kubectl get deployment scalardl-auditor-auditor -o jsonpath='{.spec.template.spec.containers[].securityContext}' | jq .
{
"allowPrivilegeEscalation": false,
"capabilities": {
"drop": [
"ALL"
]
},
"runAsNonRoot": true
}
```
=> Add default security context in Scalar DL (Ledger/Auditor) chart

charts/envoy/README.md, charts/envoy/values.schema.json, charts/envoy/values.yaml, charts/scalardb/README.md, charts/scalardb/values.schema.json, charts/scalardb/values.yaml
This PR removes unnecessary Linux capability `NET_BIND_SERVICE` from Scalar DB and Envoy chart.
`NET_BIND_SERVICE` allows binding a socket to internet domain privileged ports (port numbers less than 1024).
https://man7.org/linux/man-pages/man7/capabilities.7.html
https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
However, Scalar DB and Envoy does not bind any ports less than 1024.
So, I remove this unnecessary capability to make them more secure.
=> Remove unnecessary capabilities from Scalar DB and Envoy chert

.github/kube-audit.yaml
I updated the security configurations in the following PR.
https://github.com/scalar-labs/helm-charts/pull/118
Now,  in the Scalar Helm Charts, we use `securityContext.seccompProfile` instead of `seccomp.security.alpha.kubernetes.io/pod` annotation. This is because this annotation is deprecated now and it will be removed in the next kubernetes release.
However, the `kubeaudit` returns error as a result of `seccomp` checking since the `kubeaudit` does not understand `PodSecurityContext.seccompProfile`.
This is a known issue in the `kubeaudit`.
Please see the following comment too.
https://github.com/scalar-labs/helm-charts/pull/118#issuecomment-1189894201
So, I updated the configuration of `kubeaudit` to disable `seccomp` checking.
We can enable it again after the known issue of …
=> Disable seccomp checking in CI (kubeaudit)

charts/envoy/README.md, charts/envoy/values.schema.json, charts/envoy/values.yaml
In the current Envoy chart, it listens the two ports `service.ports.envoy.port` and `service.ports.envoy-priv.port`.
And, in the Scalar DL (Ledger and Auditor) charts, they override these two ports configuration.
However, in the Scalar DB chart, it does not override `service.ports.envoy-priv.port`.
It overrides `service.ports.envoy.port` only since Scalar DB use one port (60051) only.
So, when we deploy Scalar DB, the Envoy Service listens the port of `service.ports.envoy-priv.port` despite the port is not used.
This is because Scalar DB chart does not override the values of `service.ports.envoy-priv.port` and this configuration remains as a default value of Envoy chart.
I think this is not secure, because the unused port is open.
* Current envoy service for Scalar DB (Listens unused …
=> Remove inappropriate default values in Envoy chart

charts/scalardb/README.md, charts/scalardb/values.schema.json, charts/scalardb/values.yaml, charts/scalardl-audit/README.md, charts/scalardl-audit/values.schema.json, charts/scalardl-audit/values.yaml, charts/scalardl/README.md, charts/scalardl/values.schema.json, charts/scalardl/values.yaml
This PR removes some envoy default values from Scalar DB/DL chart.
Regarding envoy values, the same values are set as default values in Envoy chart and Scalar DB/DL chart.
In other words, there are some redundancy default values between Envoy chart and Scalar DB/DL chart.
Now, even if we update the default values of Envoy chart, it is not applied when we deploy Scalar DB/DL since Scalar DB/DL chart override that default values.
So, we need to update both Envoy and Scalar DB/DL chart if we want to update default values of Envoy chart.
I removed the above redundancy default values.
Also, I remains some values that we need to override to make them work properly.
I will add comment in each remaining values in Scalar DB/DL chart.
=> Remove unnecessary envoy default setting from each chart

charts/scalardl-audit/templates/auditor/deployment.yaml, charts/scalardl/templates/ledger/deployment.yaml
This PR adds `automountServiceAccountToken: false` in the pod definition in `deployment.yaml` of Ledger and Auditor chart.
If there is not this configuration, the `kubeaudit` returns error as follows.
```console
$ kubeaudit all -k .github/kube-audit.yaml -f <(helm template --generate-name "charts/scalardl") -m error
(snip)
-- [error] AutomountServiceAccountTokenTrueAndDefaultSA
Message: Default service account with token mounted. automountServiceAccountToken should be set to 'false' on either the ServiceAccount or on the PodSpec or a non-default service account should be used.
```
```console
$ kubeaudit all -k .github/kube-audit.yaml -f <(helm template --generate-name "charts/scalardl-audit") -m error
(snip)
-- [error] AutomountServiceAccountTokenTrueAndDefaultSA
Message: Default service …
```
=> Set `automountServiceAccountToken: false` in Ledger and Auditor chart

charts/envoy/README.md, charts/envoy/values.yaml
This PR disables Pod Security Policy by default since this feature is deprecated  and it will be removed in the next Kubernetes release.
Also, I updated the security configurations in the following PRs.
https://github.com/scalar-labs/helm-charts/pull/116
https://github.com/scalar-labs/helm-charts/pull/117
https://github.com/scalar-labs/helm-charts/pull/118
So, this PR should be merged after the above PRs are merged.
=> Disable Pod Security Policy by default in Envoy chart

charts/scalardl-audit/README.md, charts/scalardl-audit/templates/auditor/deployment.yaml, charts/scalardl-audit/values.yaml
This PR updates Auditor chart to use `40053` port for scalar-admin by default.
---
For your reference, I tested this update using Scalar DL v3.5.0 as follows.
* Headless Service
```console
$ kubectl get svc scalardl-auditor-headless
NAME                        TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                         AGE
scalardl-auditor-headless   ClusterIP   None         <none>        40051/TCP,40053/TCP,40052/TCP   89s
```
```json
$ kubectl get svc scalardl-auditor-headless -o jsonpath='{.spec.ports}' | jq .
[
{
"name": "scalardl-auditor",
"port": 40051,
"protocol": "TCP",
"targetPort": 40051
},
{
"name": "scalardl-auditor-admin",
"port": 40053,
"protocol": "TCP",
"targetPort": 40053
},
{
"name": "scalardl-auditor-priv",
"port": 40052,
"protocol": …
```
=> Update Auditor chart to use `40053` port for scalar-admin by default

charts/scalardb-graphql/README.md, charts/scalardb-graphql/templates/scalardb-graphql/prometheusrules.yaml, charts/scalardb-graphql/templates/scalardb-graphql/service.yaml, charts/scalardb-graphql/templates/scalardb-graphql/servicemonitor.yaml, charts/scalardb-graphql/values.yaml
This PR adds Service, ServiceMonitor, and PrometheusRule resources to `scalardb-graphql` chart as `scalardb` and `scalardl` charts do.
The latest build of the docker image from the `scalardb-graphql` `main` branch is needed.
I confirmed on a minikube cluster:
* Build a docker image of scalardb-graphql
```console
cd /path/to/scalardb-graphql
./gradlew docker
minikube image load ghcr.io/scalar-labs/scalardb-graphql:4.0.0-SNAPSHOT
minikube image tag ghcr.io/scalar-labs/scalardb-graphql:4.0.0-SNAPSHOT local/test/scalardb-graphql:4.0.0-SNAPSHOT
```
* Start a database in the `minikube` network and load a schema
```console
docker run -d --name cassandra-scalardb --network minikube -p 9042:9042 cassandra:3.11
java -jar scalardb-schema-loader-3.5.0.jar ...
```
* Create a custom values file
```
cat …
```
=> Add monitoring resources to scalardb-graphql chart

charts/scalardb-graphql/README.md, charts/scalardb-graphql/values.yaml
This PR updates the default Ingress paths configuration.
`pathType: Exact` is enough for the GraphQL single endpoint. And I confirmed this works with ALB.
https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types
(If it is set to `Prefix`, the ALB path becomes `/graphql OR /graphql/*`, but the second is not needed.)
=> Update default Ingress paths configuration in values.yaml

charts/envoy/Chart.yaml, charts/envoy/README.md
A new minor version of Scalar Envoy Helm Charts has been released.
This PR updates version of Scalar Envoy chart to keep main branch latest.
https://github.com/scalar-labs/helm-charts/commit/715e7ad7895a9ab0e8ef508465b41774b39fa099
=> Update chart version to keep main branch latest (Envoy)

charts/scalardl/Chart.lock, charts/scalardl/Chart.yaml, charts/scalardl/README.md, charts/scalardl/values.yaml
A new minor version of Scalar DL Ledger Helm Charts has been released.
This PR updates version of Scalar DL Ledger chart to keep main branch latest.
https://github.com/scalar-labs/helm-charts/commit/09f98fabf65bed61bcb5e6273af97164b1577fc7
=> Update chart version to keep main branch latest (Ledger)

charts/scalardl-audit/Chart.lock, charts/scalardl-audit/Chart.yaml, charts/scalardl-audit/README.md, charts/scalardl-audit/values.yaml
A new minor version of Scalar DL Auditor Helm Charts has been released.
This PR updates version of Scalar DL Auditor chart to keep main branch latest.
https://github.com/scalar-labs/helm-charts/commit/a806578e34a522f2f65e69f2b79810eded78a995
=> Update chart version to keep main branch latest (Auditor)

charts/scalardb-graphql/README.md, charts/scalardb-graphql/values.schema.json, charts/scalardb-graphql/values.yaml
This PR adds the `values.schema.json` for the `helm lint` command to the scalardb-graphql chart since it is missing in this chart only.
```console
$ helm lint ./charts/scalardb-graphql
==> Linting ./charts/scalardb-graphql
1 chart(s) linted, 0 chart(s) failed
```
=> Add values.schema.json to scalardb-graphql chart

.github/schema-loading.yaml, .github/workflows/helm_charts_scalar.yml, charts/scalardb-graphql/Chart.yaml, charts/scalardb-graphql/README.md, charts/scalardb-graphql/ci/ct-values.yaml, charts/scalardb-graphql/templates/scalardb-graphql/deployment.yaml, charts/scalardb-graphql/values.yaml
This PR updates the version of Scalar DB GraphQL to 3.6.0.
The following changes have also been made in this PR to make the probes work well and for the CI to pass.
1. liveness/readiness probes
`initialDelaySeconds` was added to liveness/readiness probes to avoid restarting pods in the initial startup.
The probe method was also changed from `httpGet` to `tcpSocket` since Scalar DB GraphQL 3.6.0 always starts (or continues) a transaction when it receives a GraphQL query and it triggers database access. The liveness/readiness probe should not affect the database.
1. schema-loading job in CI
In order for the `ct install` command to install the scalardb-graphql chart in CI, it is necessary to load a database schema into the Cassandra database since Scalar DB GraphQL requires at least one …
=> Update scalardb-graphql version to 3.6.0

.github/workflows/helm_charts_scalar.yml
This PR adds Scalar DL charts (`scalardl` and `scalardl-audit`) to the list of targets for testing of kubeaudit.
After this update, we can check Scalar DL charts using kubeaudit in the CI.
~Also, I fixed the bug of CI related to kubeaudit.~
~Now, kubeaudit does NOT check the chart of Scalar DB since it doesn't run the `helm dependency` command.~
~In this case (if we don't run `helm dependency`), it returns the following ERROR.~
```
$ kubeaudit all -k .github/kube-audit.yaml -f <(helm template --generate-name "charts/scalardb") -m error
Error: found in Chart.yaml, but missing in charts/ directory: envoy
All checks completed. 0 high-risk vulnerabilities found
```
~However kubeaudit returns `0` as an exit status despite the above error occurring.~
```
$ echo $?
0
```
~So, the CI is not …
=> Add Scalar DL chart to the list of targets for testing of kubeaudit

.github/workflows/helm_charts_scalar.yml
This PR fixes the bug of CI related to kubeaudit.
Now, kubeaudit does NOT check the chart of Scalar DB since it doesn't run the `helm dependency` command.
In this case (if we don't run `helm dependency`), it returns the following ERROR.
```
$ kubeaudit all -k .github/kube-audit.yaml -f <(helm template --generate-name "charts/scalardb") -m error
Error: found in Chart.yaml, but missing in charts/ directory: envoy
All checks completed. 0 high-risk vulnerabilities found
```
However kubeaudit returns `0` as an exit status despite the above error occurring.
```
$ echo $?
0
```
So, the CI is not failed even if the kubeaudit returns this error...
In other words, the CI was successful before despite the kubeaudit does NOT check the Scalar DB chart.
If the target chart has a dependency (in this …
=> Fix bug of CI related to the kubeaudit

charts/schema-loading/Chart.yaml, charts/schema-loading/README.md, charts/schema-loading/values.yaml
A new minor version of Scalar DL Schema Loader Helm Charts has been released.
This PR updates version of Scalar DL Schema Loader chart to keep main branch latest.
https://github.com/scalar-labs/helm-charts/commit/cb3eff9302ef474839fa5dfc64dcd6f4f2dda21c
=> Update chart version to keep main branch latest (Schema Loader)

charts/scalardb/README.md, charts/scalardb/values.yaml
This PR disables Pod Security Policy by default since this feature is removed in the latest Kubernetes release v1.25.
https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/#pod-security-changes
Also, we have already disabled Pod Security Policy by default in the Envoy chart in the following PR.
https://github.com/scalar-labs/helm-charts/pull/120
=> Disable Pod Security Policy by default in Scalar DB chart

charts/scalardb/Chart.lock, charts/scalardb/Chart.yaml, charts/scalardb/README.md, charts/scalardb/values.yaml
A new minor version of Scalar DB Helm Charts has been released.
This PR updates version of Scalar DB chart to keep main branch latest.
https://github.com/scalar-labs/helm-charts/commit/3c265f7aff8ea7319e9cdf819c3c3f935b2cb14d
=> Update chart version to keep main branch latest (Scalar DB)

.github/workflows/helm_charts_scalar.yml
In the following PR, the CI failed several times with the timeout error in the step of waiting for Cassandra starts.
https://github.com/scalar-labs/helm-charts/pull/142
I re-run it several times and finally it succeeded, but I think it is better to increase the timeout configuration.
So, I updated the timeout configuration from `60s` to `120s`.
=> Increase timeout configuration for Cassandra in the CI

docs/how-to-use-customized-configuration.md
This PR updates the document `how-to-use-customized-configuration.md`.
I added how to use the new feature of the Scalar DL Schema Loader chart that is added in the following PR.
https://github.com/scalar-labs/helm-charts/pull/139
=> Add docs how to use new feature of the Scalar DL Shema Loader chart

docs/getting-started-logging.md, docs/getting-started-monitoring.md, docs/getting-started-scalar-helm-charts.md, docs/getting-started-scalar-manager.md, docs/getting-started-scalardb.md, docs/getting-started-scalardl-auditor.md, docs/getting-started-scalardl-ledger.md
This PR updates the getting started guide of Scalar Helm Chart. The summary of updates is the following.
* Can work on any Kubernetes cluster
* In the previous document, we need to use `minikube + docker` environment. However, these new documents can work on any Kubernetes cluster since all components (Scalar products, backend DB, and client) will be deployed on the Kubernetes cluster.
* Use Marketplace instead of GitHub Packages to pull the container images.
* I added the description to get container images from AWS Marketplace or Azure Marketplace and the configuration file for each marketplace.
* Use `eclipse-temurin:8` as a client instead of `ubuntu:20.04`
* If we use `ubuntu:20.04` as a client container, we need to install `openjdk-8-jdk`, but it takes a long time. Now, we use …
=> Update getting started guide to work on any Kubernetes cluster

charts/schema-loading/templates/batchjob-schema-loading.yaml
This PR fixes the environment variable names that are used in ScalarDL Schema Loader chart internally.
In the previous chart, there is no way to pass the arbitrary environment variable from `Secret` resource.
However, in the latest chart, users can pass arbitrary environment variables to pods using `Secret` resource.
As a result, there is a possibility that the `chart internal environment variable name` and `user-defined environment variable name` will conflict.
(Note: The internally used environment variables are necessary for keeping backward compatibility.)
So, we should add prefix `HELM_SCALAR_` to the internal environment variable to make the purpose of it clear.
Also, the following document has already described that users cannot use some environment variable names (e.g., …
=> Update environment variable name in ScalarDL Schema Loader chart

charts/scalardb/Chart.yaml, charts/scalardb/README.md, charts/scalardb/values.yaml
A new patch version of ScalarDB Helm Charts has been released.
This PR updates version of ScalarDB chart to keep main branch latest.
https://github.com/scalar-labs/helm-charts/commit/c85100b274f3753b133980d107d277ce994fffce
=> Update chart version to keep main branch latest (ScalarDB v3.7.2)

charts/scalardb-graphql/Chart.yaml, charts/scalardb-graphql/README.md, charts/scalardb-graphql/values.yaml
A new patch version of ScalarDB GraphQL Helm Charts has been released.
This PR updates version of ScalarDB GraphQL chart to keep main branch latest.
https://github.com/scalar-labs/helm-charts/commit/a2fbac90fb24330eeffb7e011f3b8bc726afce33
=> Update chart version to keep main branch latest (ScalarDB GraphQL v3.7.2)

README.md
This PR adds the description of the supported Kubernetes version.
It is decided according to the test result in the following PR.
https://github.com/scalar-labs/helm-charts/pull/155
=> Add supported k8s version in the README

.github/ct-all.yaml, .github/workflows/helm_charts_scalar.yml
This PR updates the CI to run the all charts testing.
In the current CI, it only checks the updated charts only.
In other words, if there is no updated chart, CI doesn't run chart testing (ct command).
So, we cannot test if we add new Kubernetes version since it only update Kubernetes version and any charts are not updated.
To run the all charts testing even if there is no updated chart, I add the `workflow_dispatch` condition.
We can run the all charts testing manually in any time.
So, we will able to test Scalar Helm Chart when the new Kubernetes version is added.
=> Update CI to run all charts testing manually

charts/scalardb/Chart.yaml, charts/scalardb/README.md, charts/scalardb/values.yaml
A new patch version of ScalarDB Helm Charts has been released.
This PR updates the version of the ScalarDB chart to keep the main branch latest.
https://github.com/scalar-labs/helm-charts/commit/ce277d472dca843a626b43a101e929f8984e836b
=> Update chart version to keep main branch latest (ScalarDB v3.7.3)

charts/scalardb-graphql/Chart.yaml, charts/scalardb-graphql/README.md, charts/scalardb-graphql/values.yaml
A new patch version of ScalarDB GraphQL Helm Charts has been released.
This PR updates the version of the ScalarDB GraphQL chart to keep the main branch latest.
https://github.com/scalar-labs/helm-charts/commit/9d4f4521e0c7d08edecd010e121082f47a2d8eee
=> Update chart version to keep main branch latest (ScalarDB GraphQL v3.7.3)

charts/scalardb/Chart.yaml, charts/scalardb/README.md, charts/scalardb/values.yaml
A new minor version of ScalarDB Helm Charts has been released.
This PR updates the version of the ScalarDB chart to keep the main branch latest.
https://github.com/scalar-labs/helm-charts/commit/5500969b778c0316e6dd4310b9f6160d7e1d630c
=> Update chart version to keep main branch latest (ScalarDB v3.8.0)

charts/scalardb-graphql/Chart.yaml, charts/scalardb-graphql/README.md, charts/scalardb-graphql/values.yaml
A new minor version of ScalarDB GraphQL Helm Charts has been released.
This PR updates the version of the ScalarDB GraphQL chart to keep the main branch latest.
https://github.com/scalar-labs/helm-charts/commit/59bf85168b62a8236f1d9881b0fc9a7f24ce7601
=> Update chart version to keep main branch latest (ScalarDB GraphQL v3.8.0)

.github/workflows/helm_charts_scalar.yml
This PR adds the `sleep 1` command before `kubectl wait` in the CI.
The CI sometimes fails with the following error.
```shell
$ kubectl wait --for=condition=Ready --timeout=120s pod/cassandra-0
Error from server (NotFound): pods "cassandra-0" not found
```
For example, you can see it in the following action.
https://github.com/scalar-labs/helm-charts/actions/runs/3945941786/jobs/6753281153
I guess, there is a time lag between the `StatefulSet` creation and the `Pod` creation by the StatefulSet.
Also, I investigated the `kubectl wait` command. However, it seems that there is no way to handle (re-try) the `not found` error.
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#wait
So, I added the `sleep` command before the `kubectl wait` command for waiting for the pod …
=> Add sleep command before kubectl wait in the CI

docs/conf/scalar-prometheus-custom-values.yaml, docs/getting-started-logging.md
This PR updates the getting started with Loki and sample configuration for kube-prometheus-stack.
In the current getting started, we set Loki data source configuration from Web UI.
However, that configurations are not persisted anywhere.
So, if the Grafana container is restarted, that configuration is removed.
Also, in the getting started with Scalar Manager, we update the configuration of Grafana and apply it.
When this configuration applying, the Grafana pods is restarted.
So, the data source configuration of Loki that is configured from the Web UI is removed.
To avoid the above issue, I added the Loki data source configuration in the custom values file.
In this way, the data source configuration is persisted.
So, even if the Grafana pod is restarted, we can use Loki data sources …
=> Add Loki data source config in custom values file

charts/scalardb-cluster/files/grafana/scalardb_cluster_grafana_dashboard.json
This PR modifies the Grafana dashboard configuration file for ScalarDB Cluster (`scalardb_cluster_grafana_dashboard.json`). I have confirmed that Grafana is displaying the metrics correctly with the configuration. Actually, we have more metrics other than the existing Distributed Transaction Admin Service metrics, but I didn't add them because we basically don't see the Distributed Transaction Admin Service metrics very often. 
=> Modify scalardb_cluster_grafana_dashboard.json

charts/scalardb/README.md, charts/scalardb/templates/scalardb/deployment.yaml, charts/scalardb/values.schema.json, charts/scalardb/values.yaml
This PR adds a new feature that can mount any extra volumes on the ScalarDB Server pods.
For example, we can use this feature to get a heap dump file of the ScalarDB Server.
Sometimes we need to get a heap dump of JVM to investigate the ScalarDB Server issues (e.g., OOM error).
However, we cannot get the heap dump file at this time since the heap dump file is not persisted in the container.
To make the heap dump file persistent, we need to mount some volumes.
---
For your reference, we can mount `/dump` directory using this new feature in the ScalarDB Server pod as follows.
```yaml
$ cat extra-volume-scalardb-server.yaml
scalardb:
replicaCount: 1
(snip)
extraVolumes:
- name: heap-dump
emptyDir: {}
extraVolumeMounts:
- name: heap-dump
mountPath: /dump
```
```shell
helm install scalardb …
```
=> Support extra volume mount in ScalarDB Server chart

.github/workflows/helm_charts_scalar.yml
This PR updates the deprecated feature `set-output` in the GitHub Actions.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Update deprecated feature `set-output` in workflow

docs/getting-started-scalar-manager.md
This PR fixes a typo in the getting started with Scalar Manager.
Regarding the key name, `grafana.ini` is correct.
https://github.com/scalar-labs/helm-charts/blob/main/docs/conf/scalar-prometheus-custom-values.yaml#L35
https://github.com/grafana/helm-charts/blob/grafana-6.50.7/charts/grafana/values.yaml#L692
=> Fix typo of Grafana custom values

docs/getting-started-scalar-manager.md
This PR adds a requirement section in the Scalar Manager getting started guide.
Before, we pulled all images from GitHub Packages in all getting started guides. And, we created a secret resource that includes GitHub Personal Access Token (PAT) in the getting started guide of ScalarDB or ScalarDL.
So, we could pull the Scalar Manager container image using this PAT.
However, I updated the getting started guide of ScalarDB and ScalarDL in PR #147.
After that update, we pull ScalarDB/ScalarDL container images from AWS/Azure Marketplace.
So, we don't create a secret resource that includes PAT of GitHub.
In other words, there are no steps to create a secret resource that includes PAT to pull the Scalar Manager container image.
As a result, we will face the `Error: ErrImagePull` error when we …
=> Add requirement in getting started scalar manager

charts/scalardb/Chart.yaml, charts/scalardb/README.md, charts/scalardb/files/grafana/scalardb_grafana_dashboard.json, charts/scalardb/templates/scalardb/configmap.yaml, charts/scalardb/values.yaml
This PR updates the product name from `Scalar DB` to `ScalarDB` in the ScalarDB chart directory.
=> Update product name in ScalarDB chart

charts/scalardb-graphql/Chart.yaml, charts/scalardb-graphql/README.md, charts/scalardb-graphql/files/grafana/scalardb_graphql_grafana_dashboard.json, charts/scalardb-graphql/templates/scalardb-graphql/prometheusrules.yaml, charts/scalardb-graphql/values.yaml
This PR updates the product name from `Scalar DB GraphQL` to `ScalarDB GraphQL` in the ScalarDB GraphQL chart directory.
=> Update product name in ScalarDB GraphQL chart

charts/scalardl-audit/Chart.yaml, charts/scalardl-audit/README.md, charts/scalardl-audit/files/grafana/scalardl_audit_grafana_dashboard.json, charts/scalardl-audit/files/grafana/scalardl_audit_response_grafana_dashboard.json, charts/scalardl-audit/templates/auditor/configmap.yaml
This PR updates the product name from `Scalar DL` to `ScalarDL` in the ScalarDL Auditor chart directory.
=> Update product name in ScalarDL Auditor chart

charts/scalardl/README.md, charts/scalardl/templates/ledger/deployment.yaml, charts/scalardl/values.schema.json, charts/scalardl/values.yaml
This PR adds a new feature that can set an arbitrary Service Account to the ScalarDL Ledger pods.
For example, if we use a pay-as-you-go container in an EKS cluster, we need to create Service Account to grant permission to run the `AWS Marketplace Metering Service API` and specify it to `ledger.serviceAccount.serviceAccountName` in this chart. It uses the [IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) feature of AWS.
---
For your reference, you can create the Service Account to allow running `AWS Marketplace Metering Service API` as follows.
```console
eksctl create iamserviceaccount \
--name <SERVICE_ACCOUNT_NAME> \
--namespace <NAMESPACE> \
--cluster <ENTER_YOUR_CLUSTER_NAME_HERE> \ …
```
=> Allow specifying any serviceaccounts in Ledger chart

charts/scalardl-audit/README.md, charts/scalardl-audit/templates/auditor/deployment.yaml, charts/scalardl-audit/values.schema.json, charts/scalardl-audit/values.yaml
This PR adds a new feature that can set an arbitrary Service Account to the ScalarDL Auditor pods.
For example, if we use a pay-as-you-go container in an EKS cluster, we need to create Service Account to grant permission to run the `AWS Marketplace Metering Service API` and specify it to `auditor.serviceAccount.serviceAccountName` in this chart. It uses the [IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) feature of AWS.
---
For your reference, you can create the Service Account to allow running `AWS Marketplace Metering Service API` as follows.
```console
eksctl create iamserviceaccount \
--name <SERVICE_ACCOUNT_NAME> \
--namespace <NAMESPACE> \
--cluster <ENTER_YOUR_CLUSTER_NAME_HERE> \ …
```
=> Allow specifying any serviceaccounts in Auditor chart

charts/scalar-manager/README.md, charts/scalar-manager/templates/_helpers.tpl, charts/scalar-manager/templates/deployment.yaml, charts/scalar-manager/templates/role.yaml, charts/scalar-manager/templates/rolebinding.yaml, charts/scalar-manager/templates/serviceaccount.yaml, charts/scalar-manager/values.schema.json, charts/scalar-manager/values.yaml
This PR adds a new feature that can set an arbitrary Service Account to the Scalar Manager pods.
For example, if we use a pay-as-you-go container in an EKS cluster, we need to create Service Account to grant permission to run the `AWS Marketplace Metering Service API` and specify it to `serviceAccount.serviceAccountName` in this chart. It uses the [IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) feature of AWS.
Also, the Scalar Manager pod already uses Service Account to allow running the Kubernetes API from inside of Scalar Manager pod.
We cannot set two Service Accounts to one pod, so I adjusted `Role` and `Rolebinding` resource.
If we don't specify the existing Service Account, this chart generates Service Account …
=> Allow specifying any serviceaccounts in Scalar Manager chart

charts/scalardl/templates/ledger/service.yaml
This PR adds `namespace: {{ .Release.Namespace }}` configuration in the `service.yaml` file. This update make the `helm template` command with `--namespace` flag works properly.
Probably, we overlooked this point in the following PR. This PR fixes it.
https://github.com/scalar-labs/helm-charts/pull/82
=> Make namespace configurable in helm template (ScalarDL Ledger)

charts/scalardb-cluster/README.md, charts/scalardb-cluster/templates/scalardb-cluster/deployment.yaml, charts/scalardb-cluster/templates/scalardb-cluster/service.yaml, charts/scalardb-cluster/values.schema.json, charts/scalardb-cluster/values.yaml
This PR adds the GraphQL feature support to the ScalarDB Cluster chart.
Some default values are based on the current ScalarDB Cluster default configurations, but we can update some default configurations in the future based on the ScalarDB Cluster's feature updates.
=> Support GraphQL feature in ScalarDB Cluster chart

.github/workflows/helm_charts_scalar.yml
This PR updates the CI for ScalarDB Cluster.
The `ct` and `kubeval` commands get all chart names (directories) automatically in the current CI. So, we don't need to update their workflow.
However, we specify the list of chart (directory) names for the `kubeaudit` testing. So, I added the chart name `scalardb-cluster` to the list.
=> Update CI for ScalarDB Cluster

charts/scalardb-cluster/README.md, charts/scalardb-cluster/values.yaml
This PR updates the default value of `envoy.enabled`.
I disabled Envoy by default (use direct mode by default) according to the following discussion.
https://github.com/scalar-labs/misc/pull/76#issuecomment-1459667168
=> Disable envoy by default in ScalarDB Cluster chart

charts/scalardb-cluster/Chart.yaml
This PR updates the `.Chart.AppVersion` of the ScalarDB Cluster chart.
Now, ScalarDB Cluster provides SNAPSHOT version container images. So, I use these SNAPSHOT version images in the `main` branch for using/testing the latest version features in the ScalarDB Cluster chart.
https://github.com/scalar-labs/scalardb-cluster/pull/65
https://github.com/orgs/scalar-labs/packages/container/scalardb-cluster-node/84646269?tag=4.0.0-SNAPSHOT
=> Use SNAPSHOT version in latest ScalarDB Cluster chart

charts/scalardb-cluster/values.yaml
This PR fixes the comment about the default value of `scalar.db.graphql.enabled` in the `values.yaml` file of the ScalarDB Cluster chart.
We set `scalar.db.graphql.enabled` to `false` by default in the following commit of ScalarDB Cluster.
https://github.com/scalar-labs/scalardb-cluster/commit/e35e616ae79cb082314d6c88ef662138dd6001f4
So, I fixed the comment based on the above default value.
=> Fix comment in scalardb-cluster-node.properties file

charts/scalardb-cluster/README.md, charts/scalardb-cluster/values.schema.json
This PR fixes the auto generated chart docs and values schema files.
Since I forgot to update chart docs and values schema when I updated `values.yaml`, the CI failed as follows.
https://github.com/scalar-labs/helm-charts/actions/runs/4740369089/jobs/8416110130
To fix the above error, I ran the script that generates (automatically updates) chart docs and values schema.
Sorry, I overlooked it in the previous PRs.
Note: All files in this PR were generated automatically by `scripts/update-chart-docs.sh` and `scripts/update-values-schema-json.sh`.
Please take a look.
=> Fix chart docs and values schema of ScalarDB Cluster chart

index.yaml
This PR adds an entry of ScalarDL Auditor v3.7.2 chart to `index.yaml` to release this chart.
The release workflow succeeded (it didn't return errors), but the `index.yaml` was not updated by the workflow for some reason...
So, I created the index entry for ScalarDL Auditor v3.7.2 chart.
---
For your reference, I describe the details as follows.
Now, we are using `helm/chart-releaser-action@v1.2.1` in the [release workflow](https://github.com/scalar-labs/helm-charts/blob/main/.github/workflows/release.yml#L35).
And, according to the implementation of this action, it seems that this action runs three `cr` commands in the following order.
https://github.com/helm/chart-releaser-action/blob/v1.2.1/cr.sh
1. cr package
1. cr upload
1. cr index
And, from the log of workflow …
=> Update index.yaml manually for release scalardl-audit v2.5.2

charts/scalardb-cluster/values.yaml
This PR adds the default configurations of the SQL feature to `scalardbCluster.scalardbClusterNodeProperties` in the `values.yaml` file.
=> Add SQL configurations to scalardbClusterNodeProperties

docs/getting-started-scalardb.md, docs/getting-started-scalardl-auditor.md, docs/getting-started-scalardl-ledger.md
This PR adds the links to some guides for monitoring/logging to the getting started guide of ScalarDB/ScalarDL.
From the perspective of our documentation site, we want to list only necessary documents in the left pane of the documentation site. This is because, listing all documents is a bit confusing since there are a lot of product's documents.
To achieve this, we decided to list only three documents as root documents of Scalar Helm Chart.
* Getting Started with Helm Charts (ScalarDB Server)
* Getting Started with Helm Charts (ScalarDL Ledger / Ledger only)
* Getting Started with Helm Charts (ScalarDL Ledger and Auditor / Auditor mode)
However, there is no information about monitoring/logging in the above documents. So, I added links to those documents to lead users to the …
=> Add further reading part in getting started guide

docs/configure-custom-values-file.md, docs/configure-custom-values-scalardb-cluster.md, docs/configure-custom-values-scalardl-auditor.md, docs/configure-custom-values-scalardl-ledger.md, docs/how-to-deploy-scalar-products.md, docs/how-to-deploy-scalardb-cluster.md, docs/how-to-deploy-scalardl-auditor.md, docs/how-to-deploy-scalardl-ledger.md, docs/mount-files-or-volumes-on-scalar-pods.md, docs/use-secret-for-credentilas.md
This PR updates several documents to add descriptions for ScalarDB Cluster chart.
Note: At this time, we don't provide ScalarDB Cluster in AWS/Azure Marketplace. So, I don't create `Getting Started with Helm Charts (ScalarDB Cluster)` now. I would like to discuss this in the next week.
=> Add docs for ScalarDB Cluster chart

charts/scalardb-cluster/ci/scalardb-cluster-ct-values.yaml
This PR updates CI for the ScalarDB Cluster chart to use PostgreSQL instead of Cassandra. This PR is based on #212.
---
For your reference, I was able to run the `ct` command in my local environment as follows.
```shell
$ ct install --config .github/ct.yaml
Installing charts...
>>> helm version --short
>>> git rev-parse --is-inside-work-tree
>>> git merge-base origin/main HEAD
>>> git diff --find-renames --name-only 8d60921da13d070125616acfe6d06a8c09778103 -- charts
------------------------------------------------------------------------------------------------------------------------
Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
scalardb-cluster => (version: …
```
=> Update CI for ScalarDB Cluster chart to use PostgreSQL

charts/scalardb-cluster/files/grafana/scalardb_cluster_grafana_dashboard.json
This PR updates the grafana dashboard for ScalarDB Cluster. It includes the following two updates.
1. Add GraphQL metrics panels.
2. Update the dashboard (each panel) based on the adjusting result in the GUI. (After I adjusted the dashboard, I exported the JSON file from GUI.
The updated dashboard is as follows.
<details>
<summary>New dashboard</summary>
</details>
=> Update Grafana Dashboard to support GraphQL metrics

charts/envoy/Chart.yaml, charts/envoy/README.md, charts/envoy/values.yaml, charts/scalar-manager/Chart.yaml, charts/scalar-manager/README.md, charts/scalardb-graphql/Chart.yaml, charts/scalardb-graphql/README.md, charts/scalardb-graphql/values.yaml, charts/scalardb/Chart.lock, charts/scalardb/Chart.yaml, charts/scalardb/README.md, charts/scalardb/values.yaml, charts/scalardl-audit/Chart.lock, charts/scalardl-audit/Chart.yaml, charts/scalardl-audit/README.md, charts/scalardl-audit/values.yaml, charts/scalardl/Chart.lock, charts/scalardl/Chart.yaml, charts/scalardl/README.md, charts/scalardl/values.yaml, charts/schema-loading/Chart.yaml, charts/schema-loading/README.md, charts/schema-loading/values.yaml
This PR updates all charts to use SNAPSHOT version container images in the `main` branch (i.e., we will use SNAPSHOT versions container images for development and CI).
Note: The CI will be failed since several charts don't support the following updates yet.
* https://github.com/scalar-labs/scalardb/pull/780
* https://github.com/scalar-labs/scalar/pull/942
* https://github.com/scalar-labs/scalar/pull/947
I will update it in another PR.
=> Use SNAPSHOT versions in main branch

charts/scalardb/templates/scalardb/configmap.yaml, charts/scalardb/templates/scalardb/deployment.yaml
This PR renames the properties file name.
Note: This PR depends on #215.
Since we removed the `dockerize` command from the container image in the following PR, we need to update the properties file from `*.properties.tmpl` to `*.properties`.
https://github.com/scalar-labs/scalardb/pull/780
=> [scalardb] Rename properties file to run without dockerize

charts/scalardl/templates/ledger/configmap.yaml, charts/scalardl/templates/ledger/deployment.yaml
This PR renames the properties file name.
Note: This PR depends on #215.
Since we removed the `dockerize` command from the container image in the following PR, we need to update the properties file from `*.properties.tmpl` to `*.properties`.
https://github.com/scalar-labs/scalar/pull/942
=> [scalardl] Rename properties file to run without dockerize

charts/scalardl-audit/templates/auditor/configmap.yaml, charts/scalardl-audit/templates/auditor/deployment.yaml
This PR renames the properties file name.
Note: This PR depends on #215.
Since we removed the `dockerize` command from the container image in the following PR, we need to update the properties file from `*.properties.tmpl` to `*.properties`.
https://github.com/scalar-labs/scalar/pull/942
=> [scalardl-audit] Rename properties file to run without dockerize

charts/schema-loading/templates/batchjob-schema-loading.yaml, charts/schema-loading/templates/configmap.yaml
This PR renames the properties file name.
Note: This PR depends on #215.
Since we removed the `dockerize` command from the container image in the following PR, we need to update the properties file from `*.properties.tmpl` to `*.properties`.
https://github.com/scalar-labs/scalar/pull/947
=> [schema-loading] Rename properties file to run without dockerize

charts/envoy/templates/deployment.yaml
This PR adds `Readiness Probe` and `Startup Probe` in the Envoy chart.
At this time (no readiness probe), there is a possibility that the CI succeeded even if there are some problems. The `ct` command checks whether the pod status is `Ready`, and if the status is `Ready` it returns `success` in the CI. However, in the current charts, there is no `Readiness Probe` configuration. So, the pod will be the `Ready` status temporarily when the container starts even if the Envoy process will failed in the container.
As this above, There is a possibility that the `ct` command detects this temporary `Ready` state and returns `success`. To fix this issue, I added `Readiness Probe`. After this update, the pod status will be `Ready` only after Envoy returns  `Ready` in its health check endpoint. So, …
=> [envoy] Add readiness and startup probe

charts/scalardb/templates/scalardb/deployment.yaml
This PR adds `Readiness Probe` and `Startup Probe` in the ScalarDB Server chart.
At this time (no readiness probe), there is a possibility that the CI succeeded even if there are some problems. The `ct` command checks whether the pod status is `Ready`, and if the status is `Ready` it returns `success` in the CI. However, in the current charts, there is no `Readiness Probe` configuration. So, the pod will be the `Ready` status temporarily when the container starts even if the Java process will failed in the container.
As this above, There is a possibility that the `ct` command detects this temporary `Ready` state and returns `success`. To fix this issue, I added `Readiness Probe`. After this update, the pod status will be `Ready` only after ScalarDB Server returns `SERVING` in the gRPC …
=> [scalardb] Add readiness and startup probe

charts/scalardl/templates/ledger/deployment.yaml
This PR adds `Readiness Probe` and `Startup Probe` in the ScalarDL Ledger chart.
At this time (no readiness probe), there is a possibility that the CI succeeded even if there are some problems. The `ct` command checks whether the pod status is `Ready`, and if the status is `Ready` it returns `success` in the CI. However, in the current charts, there is no `Readiness Probe` configuration. So, the pod will be the `Ready` status temporarily when the container starts even if the Java process will failed in the container.
As this above, There is a possibility that the `ct` command detects this temporary `Ready` state and returns `success`. To fix this issue, I added `Readiness Probe`. After this update, the pod status will be `Ready` only after ScalarDL Ledger returns `SERVING` in the gRPC …
=> [scalardl] Add readiness and startup probe

charts/scalardl-audit/templates/auditor/deployment.yaml
This PR adds `Readiness Probe` and `Startup Probe` in the ScalarDL Auditor chart.
At this time (no readiness probe), there is a possibility that the CI succeeded even if there are some problems. The `ct` command checks whether the pod status is `Ready`, and if the status is `Ready` it returns `success` in the CI. However, in the current charts, there is no `Readiness Probe` configuration. So, the pod will be the `Ready` status temporarily when the container starts even if the Java process will failed in the container.
As this above, There is a possibility that the `ct` command detects this temporary `Ready` state and returns `success`. To fix this issue, I added `Readiness Probe`. After this update, the pod status will be `Ready` only after ScalarDL Auditor returns `SERVING` in the gRPC …
=> [scalardl-audit] Add readiness and startup probe

charts/scalar-manager/templates/deployment.yaml
This PR adds `Probes` in the Scalar Manager chart.
In the current chart, there is no health checking in Scalar Manager deployment. I think this is not good for the production environment. So, I added `Probes` for the health checking of Scalar Manager.
Note: Scalar Manager doesn't have a health check endpoint like `/health`. So, I use `/` for health checking. We are planning to add `/health` endpoint in the Scalar Manager side in the future. After we implement `/health` endpoint in Scalar Manager, I will update this chart again to use that endpoint.
=> [scalar-manager] Add probes for health checking

charts/scalardb-cluster/templates/scalardb-cluster/deployment.yaml
This PR adds `Startup Probe` in the ScalarDB Cluster chart.
Sometimes, ScalarDB Cluster takes a bit long time to start and return `Ready` state (i.e., `SERVING` in gRPC health check). However the `initialDelaySeconds` of `Readiness/Liveness Probe` is fixed value. In other words, if it takes over 60sec to start process, the pod will be killed by Kubernetes and there is a possibility that the `CrashLoopBackOff`.
To avoid this issue, we can use `Startup Probe` instead of `initialDelaySeconds`. This is a better way in the Kubernetes environment to handle health checking when that pod starting process.
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
We can run the health check before `Readiness/Liveness Probe` starts when the pod starting …
=> [scalardb-cluster] Add startup probe in ScalarDB Cluster chart

.github/workflows/helm_charts_scalar.yml
This PR adds the `--helm-extra-set-args` flag for the `ct` command in the CI.
In the current CI, a test of the ScalarDL Schema Loader chart returns `success` as a result of the test even if the pod returns an error.
1. Run the `helm install` with the `--wait` flag.
1. The job resource is created.
1. The pod of ScalarDL Schema Loader is created via the job resource.
1. The status of the pod temporarily becomes `Ready` for a moment (but not completed yet) after pod creation.
1. The `helm install` command detects this temporary `Ready` of the pod and returns `success`.
1. Even after the `helm install` command finished with `success`, the pod executes Schema Loader inside of it.
1. If the Schema Loader failed, the pod status moves to `Error`. (But, the `ct` command doesn't detect it.)
We can …
=> Add --helm-extra-set-args flag to ct command in CI

charts/scalardb-cluster/files/grafana/scalardb_cluster_grafana_dashboard.json
This PR updates the grafana dashboard for ScalarDB Cluster to add SQL metrics.
I added several sections as follows.
* SQL Total Requests
* SQL Distributed Transaction Service
* SQL Two Phase Commit Transaction Service
* SQL Metadata Service
Also, I adjusted the dashboard on the GUI and after that, I exported the JSON file from GUI.
The updated dashboard is as follows.
<details>
<summary>New dashboard</summary>
</details>
=> [scalardb-cluster] Add SQL metrics to ScalarDB Cluster dashboard

charts/scalardb-cluster/Chart.lock, charts/scalardb-cluster/Chart.yaml, charts/scalardb-cluster/README.md, charts/scalardb-cluster/values.yaml
This PR updates the chart version of the ScalarDB Cluster chart in the main branch.
We released `v1.0.0` of the ScalarDB Cluster chart, so I update the version in the main branch from `1.0.0-SNAPSHOT` to `2.0.0-SNAPSHOT`.
Also, before we were developing the ScalarDB Cluster chart in the topic branch, so we cannot access Scalar Envoy's SNAPSHOT version. However, now we merge that topic branch into the main branch and we can use Envoy's SNAPSHOT version. Therefore, I also updated Envoy's version to the SNAPSHOT version.
=> Update version of ScalarDB Cluster chart in main branch

.github/workflows/helm_charts_scalar.yml
This PR updates the version of Kubernetes and some tools in the CI.
After this CI passed, we can support new versions of Kubernetes (v1.26 and v1.27) in our Scalar Helm Chart.
=> Update version of k8s and some tools in CI

docs/how-to-deploy-scalar-manager.md, docs/how-to-deploy-scalardb-cluster.md, docs/how-to-deploy-scalardb-graphql.md, docs/how-to-deploy-scalardb.md, docs/how-to-deploy-scalardl-auditor.md, docs/how-to-deploy-scalardl-ledger.md
This PR adds the `--version` flag in the documents `How to deploy XXXX`.
If we don't specify this `--version` flag, helm uses the latest version automatically. However, there is a possibility that it causes upgrading Scalar products and Charts by accident.
To avoid upgrading by accident, it is better to specify the `--version` flag to use the same version explicitly in the same environment/system.
So, I added the `--version` flag in the documents.
=> Add --version flag to deploy document

docs/getting-started-scalardb.md, docs/getting-started-scalardl-auditor.md, docs/getting-started-scalardl-ledger.md
This PR fixes the `here documents` to support zsh environment.
This issue was reported in another PR https://github.com/scalar-labs/scalardb-cluster/pull/102#discussion_r1246368249.
=> Fix here documents to support zsh

charts/scalardb-cluster/templates/scalardb-cluster/deployment.yaml
This PR fixes the environment variable name that we use for setting of log level.
In the `log4j2.properties` file, ScalarDB Cluster uses the environment variable `SCALAR_DB_CLUSTER_LOG_LEVEL`.
https://github.com/scalar-labs/scalardb-cluster/blob/v3.10.1/node/conf/log4j2.properties
So, we must use this environment variable name in the Helm Chart for ScalarDB Clsuter.
=> [scalardb-cluster] Fix environment variable name for log level

docs/configure-custom-values-scalardl-schema-loader.md
This PR changes the link for the "Getting Started with ScalarDB" doc, which we updated in https://github.com/scalar-labs/scalardb/pull/990. The previous doc no longer exists, so that's why we need to update this link.
=> Change link for "Getting Started with ScalarDB"

README.md, docs/how-to-deploy-scalar-products.md
This PR updates the supported Kubernetes version.
At this time, each managed Kubernetes service supports the following versions.
* [EKS](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)
* v1.23 - v1.27
* [AKS](https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions)
* v1.25 - v1.28
So, I updated the supported Kubernetes versions that the Scalar Helm Chart supports based on the above versions.
Also, we test these new versions in our CI as follows.
https://github.com/scalar-labs/helm-charts/actions/runs/6155343603
=> Update supported Kubernetes version

docs/configure-custom-values-scalardb-cluster.md
This PR fixes the broken link in the document.
The linked document was updated before.
---
@josh-wong 
I have one question about the document.
We can see the same document in both GitHub and Scalar Doc Site as follows.
- https://github.com/scalar-labs/scalardb-cluster/blob/main/docs/scalardb-cluster-configurations.md
- https://scalardb.scalar-labs.com/docs/latest/scalardb-cluster/scalardb-cluster-configurations/
In this case, which URL should we set in the document if we want to link other documents from a document?
In this PR I used GitHub's URL. Is it OK to use GitHub's URL when I link some other documents from one document?
If we should use the Scalar Doc Site URL, I will update this PR.
=> Fix broken link in configure ScalarDB Cluster doc

.github/workflows/helm_charts_scalar.yml
This PR fixes the following two issues.
At this time, the `helm lint` command that is called in the `ct lint` command fail as follows.
```console
>>> helm lint charts/scalardb-analytics-postgresql --values charts/scalardb-analytics-postgresql/ci/scalardb-analytics-postgresql-ct-values.yaml --timeout 300s
Error: unknown flag: --timeout
Error: failed linting charts: failed processing charts
```
The root cause is `the ct command cannot treat extra args properly`. In other words, `ct lint` command passes the invalid option `--timeout` to the `helm lint` command. The `--timeout` is supported in `helm install` or `helm uninstall` etc. But, `helm lint` does not support `--timeout` option. So, the `helm lint` command that called via `ct lint` with `--timeout` option (invalid option) failed as …
=> Update CI to fix error of "ct lint" command

docs/configure-custom-values-scalardb-cluster.md, docs/configure-custom-values-scalardb-graphql.md
This PR fixes the wrong sample configurations. The `affinity:` is missing.
N/A
* Update the wrong sample configuration in the document.
N/A
N/A
=> Fix wrong sample configuration

docs/getting-started-monitoring.md
This PR revised the "Getting Started with Helm Charts (Monitoring using Prometheus Operator)" document to add the description about supporting Scalar Manager to collect CPU and memory resources.
Scalar Manager relies on Prometheus Stack to do so and some configurations need to be set correctly.
N/A
- revised https://github.com/scalar-labs/helm-charts/blob/main/docs/getting-started-monitoring.md
Added description to "Getting Started with Helm Charts (Monitoring using Prometheus Operator)" to support Scalar Manager to collect the CPU and memory resources
=> Revise the `Getting Started Monitoring` guide to support Scalar Manager

docs/conf/scalar-loki-stack-custom-values.yaml
This PR adds a configuration to `scalar-loki-stack-custom-values.yaml` to make Loki to scrape the logs of the pods that run scalar-admin-for-kubernetes. This is an important configuration because the results of scalar-admin-for-kubernetes are displayed as logs.
N/A
- revised `scalar-loki-stack-custom-values.yaml`
=> Revise scalar-loki-stack-custom-values.yaml to scrape the logs of scalar-admin-for-kubernetes

charts/schema-loading/templates/batchjob-schema-loading.yaml
Note: We will apply this update to schema-loading chart v2. In other words, we don't apply this update to the `main` branch. So, I changed the target branch.
This PR updates the path of `database.properties` for ScalarDL Schema Loader.
To support OpenShift as a platform of ScalarDL v3, we updated the file path of `database.properties` in the following PR on the ScalarDL side.
https://github.com/scalar-labs/scalar/pull/1112
So, we have to update the file path of `database.properties` on the Helm Chart side too.
* https://github.com/scalar-labs/scalar/pull/1112
* Update file path from `./database.properties` to `/tmp/database.properties`.
N/A
N/A
=> [scalardl-schema-loader] Support OpenShift (ScalarDL v3)

charts/envoy/README.md, charts/envoy/templates/deployment.yaml, charts/envoy/values.schema.json, charts/envoy/values.yaml
This PR adds TLS support in the Scalar Envoy chart.
In this update, users can configure TLS in both downstream and upstream connections respectively.
```console
[Client] ---(downstream connections)---> [Envoy] ---(upstream connections)---> [ScalarDB/ScalarDL]
```
* https://github.com/scalar-labs/scalar-envoy/pull/28
* I updated the Scalar Envoy to support TLS both downstream and upstream connections.
* https://github.com/scalar-labs/docs-internal-orchestration/pull/14
* I updated the document that is related to this PR. You can see the usage of this new feature and the getting started guide.
* Add new values to configure the TLS configurations.
* Mount key/cert file to use TLS connections between client and Envoy in the Deployment manifest.
N/A
Support TLS configuration in the Scalar …
=> [envoy] Support TLS in Scalar Envoy chart

.github/postgresql.yaml
This PR updates the configuration of PostgreSQL for CI.
Recently, bitnami releases a new major version of helm chart for PostgreSQL.
https://github.com/bitnami/charts/tree/main/bitnami/postgresql#to-1500
It includes backward-incompatible updates and it causes error of PostgreSQL.
Some security configurations are changed to more strict.
```console
postgresql 07:12:47.96 INFO  ==> Initializing PostgreSQL database...
mkdir: cannot create directory '/bitnami/postgresql/data': Permission denied
```
Since the security configuration was made more strict, the container cannot create a new directory under the `/bitnami/` directory.
So, I update to use `/tmp` directory instead of `/bitnami/`.
I think there is no problem if we use the `/tmp` directory because we use this PostgreSQL temporarily for …
=> Update configuration of PostgreSQL for CI to use /tmp directory

charts/scalardb-cluster/README.md, charts/scalardb-cluster/templates/scalardb-cluster/deployment.yaml, charts/scalardb-cluster/values.schema.json, charts/scalardb-cluster/values.yaml
This PR adds TLS support in the ScalarDB Cluster chart.
In this update, users can configure TLS features and set key/cert files for ScalarDB Cluster.
Note: You need to enable the wire encryption feature on the ScalarDB Cluster side by setting `scalar.db.cluster.tls.enabled=true` in the `scalardbCluster.scalardbClusterNodeProperties` in your custom values file.
* Indirect mode of Java Client SDK or using gRPC directly
```console
[Client] ---> [Envoy] ---(TLS)---> [ScalarDB Cluster]
```
* Direct Kubernetes mode of Java Client SDK
```console
[Client] ---(TLS)---> [ScalarDB Cluster]
```
* https://github.com/scalar-labs/scalar-envoy/pull/28
* I updated the Scalar Envoy to support TLS both downstream and upstream connections.
* https://github.com/scalar-labs/helm-charts/pull/253
* I updated the …
=> [scalardb-cluster] Support TLS in ScalarDB Cluster chart

charts/scalardl/README.md, charts/scalardl/templates/ledger/deployment.yaml, charts/scalardl/values.schema.json, charts/scalardl/values.yaml
This PR adds TLS support in the ScalarDL Ledger chart.
In this update, users can configure TLS features and set key/cert files for ScalarDL Ledger.
Note: You need to enable the wire encryption feature on the ScalarDL Ledger side by setting `scalar.dl.ledger.server.tls.enabled=true` in the `ledger.ledgerProperties` in your custom values file.
```console
[Client] ---> [Envoy] ---(TLS)---> [ScalarDL Ledger]
```
* https://github.com/scalar-labs/scalar-envoy/pull/28
* I updated the Scalar Envoy to support TLS both downstream and upstream connections.
* https://github.com/scalar-labs/helm-charts/pull/253
* I updated the Helm Chart of Scalar Envoy to support TLS between Envoy and ScalarDL Ledger.
* https://github.com/scalar-labs/docs-internal-orchestration/pull/14
* I updated the document that …
=> [scalardl-ledger] Support TLS in ScalarDL Ledger chart

charts/scalardl-audit/README.md, charts/scalardl-audit/templates/auditor/deployment.yaml, charts/scalardl-audit/values.schema.json, charts/scalardl-audit/values.yaml
This PR adds TLS support in the ScalarDL Auditor chart.
In this update, users can configure TLS features and set key/cert files for ScalarDL Auditor.
Note: You need to enable the wire encryption feature on the ScalarDL Auditor side by setting `scalar.dl.auditor.server.tls.enabled=true` and `scalar.dl.auditor.tls.enabled=true` in the `auditor.auditorProperties` in your custom values file.
```console
+---(TLS)---> [ScalarDL Ledger] <---(TLS)------------------+
|                                                          |
[Client] ---> [Envoy] ---+                                                          |
|                                                          |
+---(TLS)---> [ScalarDL Auditor] ---(Recovery operation)---+
```
* https://github.com/scalar-labs/scalar-envoy/pull/28
* I …
=> [scalardl-auditor] Support TLS in ScalarDL Auditor chart

charts/scalar-admin-for-kubernetes/README.md, charts/scalar-admin-for-kubernetes/templates/_helpers.tpl, charts/scalar-admin-for-kubernetes/values.schema.json, charts/scalar-admin-for-kubernetes/values.yaml
This PR adds TLS support in the Scalar Admin for Kubernetes chart.
In this update, users can mount a root CA certificate on the pod of Scalar Admin for Kubernetes.
Then, users can specify the root CA certificate by using the `--ca-root-cert-path` option and run a pause request with TLS as follows.
```console
[Scalar Admin for Kubernetes] ---> (TLS)---> [ScalarDB Cluster / ScalarDL]
```
* https://github.com/scalar-labs/docs-internal-orchestration/pull/21
* I updated the document that is related to this PR.
* Add new values to specify the name of the secret resource including root CA certificate.
* Mount root CA certificate file on Pod to use TLS connections between Scalar Admin for Kubernetes and ScalarDB Cluster/ScalarDL.
N/A
Support TLS configuration in the Scalar Admin for Kubernetes …
=> [scalar-admin-for-kubernetes] Support TLS in Scalar Admin for Kubernetes chart

charts/scalar-admin-for-kubernetes/README.md
This PR fix typo.
It's a very minor thing, but this typo (difference between `values.yaml comment` and `README`) cause the CI error.
https://github.com/scalar-labs/helm-charts/actions/runs/8655786113/job/23735277413
So, we have to fix it to run the CI properly.
* https://github.com/scalar-labs/helm-charts/actions/runs/8655786113/job/23735277413
* Fix typo and keep consistency between `values.yaml` and `README`.
N/A
N/A
=> [scalar-admin-for-kubernetes] Fix typo in README

charts/scalardl/README.md, charts/scalardl/templates/ledger/certmanager.yaml, charts/scalardl/templates/ledger/deployment.yaml, charts/scalardl/values.schema.json, charts/scalardl/values.yaml
This PR updates ScalarDL Ledger chart to support cert-manager.
- https://github.com/scalar-labs/docs-internal-orchestration/pull/24
- You can see the documents that describe how to use these new features in this PR.
- https://github.com/scalar-labs/helm-charts/pull/262
- If you use self-signed CA, this chart deploy self-signed CA. And, Scalar Envoy chart refer it to generate certificate for Envoy.
Mainly, this PR adds/updates the following features (manifests):
1. Deploy a `Certificate` resource for cert-manager by using `charts/scalardl/templates/ledger/certmanager.yaml`.
2. Deploy self-signed CA and create certificate for ScalarDL Ledger if you don't specify any `Issuer` resources in `issuerRef` configuration.
- If you deploy Scalar Envoy as a sub chart of this …
=> [scalardl-ledger] Support cert-manager in ScalarDL Ledger chart

charts/scalardl-audit/README.md, charts/scalardl-audit/templates/auditor/certmanager.yaml, charts/scalardl-audit/templates/auditor/deployment.yaml, charts/scalardl-audit/values.schema.json, charts/scalardl-audit/values.yaml
This PR updates ScalarDL Auditor chart to support cert-manager.
- https://github.com/scalar-labs/docs-internal-orchestration/pull/24
- You can see the documents that describe how to use these new features in this PR.
- https://github.com/scalar-labs/helm-charts/pull/262
- If you use self-signed CA, this chart deploy self-signed CA. And, Scalar Envoy chart refer it to generate certificate for Envoy.
Mainly, this PR adds/updates the following features (manifests):
1. Deploy a `Certificate` resource for cert-manager by using `charts/scalardl-audit/templates/auditor/certmanager.yaml`.
2. Deploy self-signed CA and create certificate for ScalarDL Auditor if you don't specify any `Issuer` resources in `issuerRef` configuration.
- If you deploy Scalar Envoy as a sub chart of …
=> [scalardl-auditor] Support cert-manager in ScalarDL Auditor chart

charts/scalardb/ci/scalardb-ct-values.yaml
Recently, we updated the visibility of the ScalarDB Server container image from `public` to `private`.
https://github.com/orgs/scalar-labs/packages/container/package/scalardb-server
The old CI assumes that the ScalarDB Server container image is public. In other words, we don't set credentials for the ScalarDB Server chart in the CI. So, the CI failed in the `main` branch.
To resolve this issue, I set credentials (`reg-docker-secrets`) in the custom values file for CI.
N/A
- Add a secret resource configuration in the custom values file that is used in CI.
N/A
N/A
=> Fix CI error of ScalarDB Server chart

.github/workflows/helm_charts_scalar.yml, README.md
This PR updates the Kubernetes version in the CI.
Also, updated the `Supported Kubernetes Version` section in the `README`. Now, we have an official document that describes `Supported Kubernetes Versions`. So, I updated the `README` to refer to the official document.
In addition, I will update the supported Kubernetes version from `1.26 - 1.30` to `1.27 - 1.31` on the official document side in another PR.
- https://github.com/scalar-labs/docs-internal-scalardb/pull/421
- I updated the official document in this PR. 
- Update Kubernetes versions in `.github/workflows/helm_charts_scalar.yml`.
- Update `README.md` to refer to the [official document](https://scalardb.scalar-labs.com/docs/latest/requirements/#kubernetes).
Basically, we decide on which Kubernetes versions are …
=> Add new version k8s in CI

charts/scalardb-cluster/README.md, charts/scalardb-cluster/templates/scalardb-cluster/deployment.yaml, charts/scalardb-cluster/values.schema.json, charts/scalardb-cluster/values.yaml
This PR updates the ScalarDB Cluster Helm Chart to support Azure Marketplace.
To list ScalarDB Cluster on the Azure Marketplace, we have to update our helm chart based on the rules of Azure Marketplace. So, I updated ScalarDB Cluster chart as follows:
- Add `global.azure.*` in the `values.yaml` file.
- Add the `azure-extensions-usage-release-identifier` label in the `deployment.yaml` to trace pods and charge license fees by Azure.
You can see what we need to list products on the Azure Marketplace in the following Azure document.
- [Update the Helm chart](https://learn.microsoft.com/en-us/partner-center/marketplace-offers/azure-container-technical-assets …
=> [scalardb-cluster] Support Azure Marketplace

charts/envoy/README.md, charts/envoy/templates/deployment.yaml, charts/envoy/values.schema.json, charts/envoy/values.yaml
This PR updates the Envoy Helm Chart to support Azure Marketplace.
To list Scalar products (ScalarDB Cluster and ScalarDL) on the Azure Marketplace, we have to update our helm chart based on the rules of Azure Marketplace. So, I updated Envoy chart as follows:
Also, I added the condition (if statement) based on the value of `global.platform`. Basically, Envoy chart is used as `subchart` from Scalar products charts (main charts). So, this `global.platform` value is passed from the main chart. However, we must set default value in `values.yaml` on the Envoy chart side.
You can see more details on the Azure Marketplace support on the ScalarDB Cluster's PR …
=> [envoy] Support Azure Marketplace

charts/scalardl/README.md, charts/scalardl/templates/ledger/deployment.yaml, charts/scalardl/values.schema.json, charts/scalardl/values.yaml
This PR updates the ScalarDL Ledger Helm Chart to support Azure Marketplace.
To list ScalarDL Ledger on the Azure Marketplace, we have to update our helm chart based on the rules of Azure Marketplace. So, I updated ScalarDL Ledger chart as follows:
- Add `global.azure.*` in the `values.yaml` file.
- Add the `azure-extensions-usage-release-identifier` label in the `deployment.yaml` to trace pods and charge license fees by Azure.
You can see what we need to list products on the Azure Marketplace in the following Azure document.
- [Update the Helm chart](https://learn.microsoft.com/en-us/partner-center/marketplace-offers/azure-container-technical-assets-ku …
=> [scalardl-ledger] Support Azure Marketplace

charts/scalardl-audit/README.md, charts/scalardl-audit/templates/auditor/deployment.yaml, charts/scalardl-audit/values.schema.json, charts/scalardl-audit/values.yaml
This PR updates the ScalarDL Auditor Helm Chart to support Azure Marketplace.
To list ScalarDL Auditro on the Azure Marketplace, we have to update our helm chart based on the rules of Azure Marketplace. So, I updated ScalarDL Auditor chart as follows:
- Add `global.azure.*` in the `values.yaml` file.
- Add the `azure-extensions-usage-release-identifier` label in the `deployment.yaml` to trace pods and charge license fees by Azure.
You can see what we need to list products on the Azure Marketplace in the following Azure document.
- [Update the Helm chart](https://learn.microsoft.com/en-us/partner-center/marketplace-offers/azure-container-technical-assets …
=> [scalardl-auditor] Support Azure Marketplace

.github/workflows/helm_charts_scalar.yml
This PR updates the versions of Kubernetes in the CI.
- Add `1.32` which is the latest version of Kubernetes.
- Remove `1.27` which is already the EoL version.
- I confirmed that each major managed Kubernetes does not support `1.27` now.
- [EKS](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)
- [AKS](https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar)
- [GKE](https://cloud.google.com/kubernetes-engine/docs/release-notes#current_versions)
- [OKE](https://docs.oracle.com/en-us/iaas/Content/ContEng/Concepts/contengaboutk8sversions.htm)
N/A
- Add Kubernetes `1.32`.
- Remove Kubernetes `1.27` since it has already been EoL.
N/A
N/A
=> Update k8s versions in CI

charts/scalardl-audit/README.md, charts/scalardl-audit/ci/scalardl-auditor-ct-values.yaml, charts/scalardl-audit/values.yaml
This PR changes the default container image in the ScalarDL Auditor chart. The previous default image is only for Scalar internal developers. In other words, users cannot pull that image. So, we decided to change the default image to the BYOL version image. Note that users still need the license key to run this image after they pull it.
N/A
- Change the default container image name from `ghcr.io/scalar-labs/scalar-auditor` to `ghcr.io/scalar-labs/scalardl-auditor-byol`.
N/A
Change the default container image name of ScalarDL Auditor.
=> [scalardl-auditor] Change default container image

charts/scalardl/README.md, charts/scalardl/values.yaml
This PR changes the default container image in the ScalarDL Ledger chart. The previous default image is only for Scalar internal developers. In other words, users cannot pull that image. So, we decided to change the default image to the OSS version image.
N/A
- Change the default container image name from `ghcr.io/scalar-labs/scalar-ledger` to `ghcr.io/scalar-labs/scalardl-ledger`.
N/A
Change the default container image name of ScalarDL Ledger.
=> [scalardl-ledger] Change default container image

charts/scalar-manager/README.md, charts/scalar-manager/templates/_helpers.tpl, charts/scalar-manager/templates/scalar-manager/configmap.yaml, charts/scalar-manager/templates/scalar-manager/deployment.yaml, charts/scalar-manager/templates/scalar-manager/service.yaml, charts/scalar-manager/templates/scalar-manager/serviceaccount.yaml, charts/scalar-manager/values.schema.json, charts/scalar-manager/values.yaml
This PR updates the Scalar Manager Helm Chart to support Azure Marketplace.
N/A
Mainly, this PR has two updates:
1. Support Azure Marketplace Pay As You Go listing.
1. Add the root key `scalarManager` in the `values.yaml` file to make `createUIDefinition.json` and `mainTemplate.json` simple.
To list Scalar Manager on the Azure Marketplace, we have to update our helm chart based on the rules of Azure Marketplace. So, I updated Scalar Manager chart as follows:
- Add `global.azure.*` in the `values.yaml` file.
You can see what we need to list products on the Azure Marketplace in the following Azure document.
- [Update the Helm …
=> [scalar-manager] Support Azure Marketplace

.github/workflows/release.yml
This PR fixes the error in the release workflow.
Now, we have Scalar Monitoring Stack helm charts, and they depend on other community helm charts, Prometheus, Grafana, Loki, and Alloy.
So, we need to add the Helm repositories of those charts in the release workflow.
Please take a look when you have time!
- https://github.com/scalar-labs/helm-charts/actions/runs/14633020472/job/41058688388
- Add `helm add` command in the release workflow.
N/A
N/A
=> Add helm repo add commands for Monitoring Stack in release workflow

.github/workflows/helm_charts_scalar.yml
This PR fixes the issue of CI.
In the current CI for charts other than Scalar Monitoring Stack, we don't need to check the Scalar Monitoring Stack charts.
However, in that CI, it selects the target charts from the directory information by using the `ls charts` command, which includes Scalar Monitoring Stack charts as a command result.
This causes the CI error like https://github.com/scalar-labs/helm-charts/actions/runs/15011694828/job/42181525214?pr=294.
To fix this issue, I excluded the Scalar Monitoring Stack charts from the CI for charts other than Scalar Monitoring Stack charts.
- https://github.com/scalar-labs/helm-charts/actions/runs/15011694828/job/42181525214?pr=294
- Exclude Scalar Monitoring Stack charts by using the `ls charts | grep -v -e "-monitoring$"` …
=> Exclude monitoring charts from CI for other charts

charts/scalar-manager/README.md, charts/scalar-manager/templates/scalar-manager/service.yaml, charts/scalar-manager/values.schema.json, charts/scalar-manager/values.yaml
This PR adds the annotations configuration support for the Service resource.
Now, you can set arbitrary annotations to the Service resource.
N/A
- Add new values `scalarManager.web.service.annotations`.
- Set annotations in the `service.yaml` file.
N/A
N/A
=> [scalar-manager] Support annotations for Service resource

.github/workflows/helm_charts_scalar.yml, charts/scalar-manager/README.md, charts/scalar-manager/values.schema.json, charts/scalar-manager/values.yaml
This PR adds the `affinity:` configuration in the `values.yaml` file.
Actually, we can set `affinity` to the Deployment resource (in `deployment.yaml`) because the `deployment.yaml` file already have the affinity configuration.
However, from the user perspective, I think it would be better to set `affinity: {}` as a default value in the `values.yaml` file so that users know they can set the affinity configuration to the Scalar Manager pod.
N/A
- Add `affinity: {}` as a default value in the `values.yaml` file.
N/A
N/A
=> [scalar-manager] Add affinity in `values.yaml` file

charts/scalar-manager/templates/scalar-manager/clusterrole.yaml
This PR removes unnecessary roles from Scalar Manager chart.
Previously, we use use the `Scalar Admin for Kubernetes` helm chart to pause Scalar products from Scalar Manager. In other words, Scalar Manager deploys the `Scalar Admin for Kubernetes` helm chart by using the `helm install` command. And, to deploy the `Scalar Admin for Kubernetes` helm chart, Scalar Manager needed to have several roles (permissions).
However, now Scalar Manager does not use the `Scalar Admin for Kubernetes` helm chart (i.e., it does not run the `helm install` command). Instead of that, Scalar Manager uses the `Scalar Admin for Kubernetes` library directly in its internal.
Therefore, we don't need to allow several permissions to Scalar Manager for deploying `Scalar Admin for Kubernetes` helm chart. This PR …
=> [scalar-manager] Remove unnecessary Roles

charts/scalar-manager/README.md, charts/scalar-manager/templates/scalar-manager/service.yaml, charts/scalar-manager/values.schema.json, charts/scalar-manager/values.yaml
This PR changes `How to configure the ports configuration of service resource`.
The main reason is that the previous configuration differs from other Scalar Helm Charts a little.
From the users (how to configure) and maintenance perspective, I want to use the same way as long as possible (i.e., I want to keep consistency between several Scalar Helm Charts).
This updated way is the same way as Envoy, ScalarDB Cluster, and ScalarDL.
- Envoy
- https://github.com/scalar-labs/helm-charts/blob/envoy-2.6.0/charts/envoy/values.yaml#L58-L65
- https://github.com/scalar-labs/helm-charts/blob/envoy-2.6.0/charts/envoy/templates/service.yaml#L12-L16
- ScalarDB Cluster
- https://github.com/scalar-labs/helm-charts/blob/scalardb-cluster-1.7.1/charts/scalardb-cluster/values.yaml#L204-L211
- …
=> [scalar-manager] Update how to configure service ports

charts/scalardl-audit/README.md, charts/scalardl-audit/templates/auditor/deployment.yaml, charts/scalardl-audit/values.schema.json, charts/scalardl-audit/values.yaml
This PR supports the HMAC authentication method in ScalarDL Auditor chart.
The previous Helm Chart assumes that ScalarDL has only one authentication method `digital-signature`. So, it always tries to mount `auditor-keys` that include a private key and certificate.
However, if users use the HMAC authentication method such a secret is not necessary, and this chart does not need to mount the `auditor-keys` that include a private key and certificate.
This PR introduces the new parameter `auditor.authentication.method`. If you don't specify the `hmac` (i.e., use `digital-signature` that is the default value), this chart tries to mount a secret `auditor-keys`. This is a default behavior, and it's backward-compatible.
If you specify the `hmac`, this chart does not try to mount the secret …
=> [scalardl-auditor] Support HMAC authentication method

charts/scalardl-ledger-monitoring/README.md, charts/scalardl-ledger-monitoring/values.schema.json, charts/scalardl-ledger-monitoring/values.yaml
This PR updates the default configuration of `kube-state-metrics`.
Basically, we assume that the ScalarDL Ledger Monitoring chart collects metrics from the same namespace only as itself is deployed (i.e, it collects metrics of ScalarDL Ledger that is deployed in the same namespace as ScalarDL Ledger Monitoring).
However, in the current default value, `kube-state-metrics` collects metrics from all namespaces. Also, it requires a bit stronger permissions that are applied by using `ClusterRole`.
This PR sets (limits) the target namespace to the same namespace only as itself is deployed, and disables deploying unnecessary `ClusterRole`.
N/A
- Set the target namespace to the release namespace only.
- Disable deploying unnecessary `ClusterRole`.
N/A
N/A
=> [scalardl-ledger-monitoring] Collect metrics from same namespace only

charts/scalardl-auditor-monitoring/README.md, charts/scalardl-auditor-monitoring/values.schema.json, charts/scalardl-auditor-monitoring/values.yaml
This PR updates the default configuration of `kube-state-metrics`.
Basically, we assume that the ScalarDL Auditor Monitoring chart collects metrics from the same namespace only as itself is deployed (i.e, it collects metrics of ScalarDL Auditor that is deployed in the same namespace as ScalarDL Auditor Monitoring).
However, in the current default value, `kube-state-metrics` collects metrics from all namespaces. Also, it requires a bit stronger permissions that are applied by using `ClusterRole`.
This PR sets (limits) the target namespace to the same namespace only as itself is deployed, and disables deploying unnecessary `ClusterRole`.
N/A
- Set the target namespace to the release namespace only.
- Disable deploying unnecessary `ClusterRole`.
N/A
N/A
=> [scalardl-auditor-monitoring] Collect metrics from same namespace only

charts/scalardb-cluster/README.md, charts/scalardb-cluster/templates/scalardb-cluster/deployment.yaml, charts/scalardb-cluster/templates/scalardb-cluster/validate-values.yaml, charts/scalardb-cluster/values.schema.json, charts/scalardb-cluster/values.yaml
This PR adds a new configuration `scalardbCluster.podLabels`.
By using this configuration, users can set arbitrary labels to the pods as follows:
- Values file
```yaml
scalardbCluster:
podLabels:
foo: bar
bar: baz
```
- Generated deployment resource
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
template:
metadata:
labels:
app.kubernetes.io/name: scalardb-cluster
app.kubernetes.io/instance: test
app.kubernetes.io/app: scalardb-cluster
bar: baz
foo: bar
```
N/A
- Add new configuration `scalardbCluster.podLabels`.
N/A
Added a new configuration `scalardbCluster.podLabels`. You can set arbitrary labels to pods.
=> [scalardb-cluster] Support User Labels

charts/scalardl/README.md, charts/scalardl/templates/ledger/deployment.yaml, charts/scalardl/templates/ledger/validate-values.yaml, charts/scalardl/values.schema.json, charts/scalardl/values.yaml
This PR adds a new configuration `ledger.podLabels` and `ledger.podAnnotations`.
By using this configuration, users can set arbitrary labels and annotations to the pods as follows:
- Values file
```yaml
ledger:
podAnnotations:
foo: bar
bar: baz
podLabels:
foo: bar
bar: baz
app.kubernetes.io/name: foo
app.kubernetes.io/app: bar
app.kubernetes.io/instance: baz
```
- Generated deployment resource
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
selector:
matchLabels:
app.kubernetes.io/name: scalardl
app.kubernetes.io/instance: test
app.kubernetes.io/app: ledger
template:
metadata:
annotations:
checksum/config: d16b9e671f1d185b78cbe2a1e92d559b39dd3e55cb180df9bb2fa863b138e1b1
bar: baz
foo: bar
labels:
app.kubernetes.io/app: ledger
app.kubernetes.io/instance: test
app.kubernetes.io/name: …
```
=> [scalardl-ledger] Support User Labels and Annotations

charts/scalar-manager/README.md, charts/scalar-manager/templates/scalar-manager/deployment.yaml, charts/scalar-manager/templates/scalar-manager/validate-values.yaml, charts/scalar-manager/values.yaml
This PR adds a new function to merge `user specified labels` and `selector labels`.
In the current (old) implementation, there is a possibility that the value of `scalarManager.podLabels` overrides the selector labels, and it causes the Deployment and Pod to not work properly.
To avoid such issues, I added the merge function.
By using this merge function, this chart prevents overriding the selector labels by user specified labels as follows:
- Values file
```yaml
scalarManager:
podLabels:
foo: bar
bar: baz
app.kubernetes.io/name: foo
app.kubernetes.io/app: bar
app.kubernetes.io/instance: baz
```
- Generated deployment resource
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
selector:
matchLabels:
app.kubernetes.io/name: scalar-manager
app.kubernetes.io/instance: test …
```
=> [scalar-manager] Merge user labels and selector labels

charts/scalardl/templates/ledger/service.yaml
This PR add a new service resource `scalardl-ledger-endpoint` to access ScalarDL Ledger directly from clients without Envoy.
Previously, the Envoy proxy is mandatory if users access ScalarDL Ledger from the outside of Kubernetes.
However, the additional 1 hop (i.e., Envoy proxy) from the network perspective, it might have a performance impact.
Therefore, we decided to make the Envoy proxy optional.
In this case, we need to add a new service to access ScalarDL Ledger directly from clients without Envoy.
N/A
- Add a new Service `scalardl-ledger-endpoint` to access ScalarDL Ledger directly without Envoy.
- Minor improvement for the existing Headless Service.
If you set `envoy.enabled` to `true` in the values file, you can see the Envoy pod and Envoy service as follows. …
=> [scalardl-ledger] Make Envoy optional
