scalar-labs/helm-charts

- charts/scalardl/Chart.yaml
- charts/scalardl/README.md
- charts/scalardl/templates/envoy/deployment.yaml
- charts/scalardl/templates/ledger/deployment.yaml
- charts/scalardl/values.yaml
https://scalar-labs.atlassian.net/browse/DLT-8790
Add `preStop` for graceful shutdown.
ref: https://github.com/scalar-labs/scalar-envoy/pull/10
- envoy
- Add `post helthcheck`
- Add `sleep`
> Add prestop for graceful shutdown envoy pods

- charts/scalardl/Chart.yaml
- charts/schema-loading/Chart.yaml
- charts/schema-loading/README.md
- charts/schema-loading/templates/batchjob-schema-loading.yaml
- charts/schema-loading/values.yaml
Add DynamoDB base resource unit option.
Option: `dynamoBaseResourceUnit`
Default value is 10.
> Add DynamoDB base resource unit option

- README.md
- charts/scalardb/.helmignore
- charts/scalardb/Chart.yaml
- charts/scalardb/README.md
- charts/scalardb/README.md.gotmpl
- charts/scalardb/files/scalardb_grafana_dashboard.json
- charts/scalardb/templates/_helpers.tpl
- charts/scalardb/templates/config-map.yaml
- charts/scalardb/templates/configmap.yaml
- charts/scalardb/templates/deployment.yaml
- charts/scalardb/templates/prometheusrules.yaml
- charts/scalardb/templates/service.yaml
- charts/scalardb/templates/servicemonitor.yaml
- charts/scalardb/values.yaml
This PR contains the Helm chart of Scalar DB server. Please take a look!
Thank you.
> Add Helm chart for Scalar DB

- charts/scalardb/files/grafana/envoy_grafana_dashboard.json
- charts/scalardb/files/grafana/scalardb_grafana_dashboard.json
- charts/scalardb/templates/envoy/configmap.yaml
- charts/scalardb/templates/scalardb/configmap.yaml
- charts/scalardl-audit/files/grafana/envoy_grafana_dashboard.json
- charts/scalardl-audit/files/grafana/scalardl_audit_grafana_dashboard.json
- charts/scalardl-audit/files/grafana/scalardl_audit_response_grafana_dashboard.json
- charts/scalardl-audit/templates/auditor/configmap.yaml
- charts/scalardl-audit/templates/envoy/configmap.yaml
- charts/scalardl/files/grafana/envoy_grafana_dashboard.json
- charts/scalardl/files/grafana/scalardl_grafana_dashboard.json
- charts/scalardl/files/grafana/scalardl_response_grafana_dashboard.json
- charts/scalardl/templates/envoy/configmap.yaml
- charts/scalardl/templates/ledger/configmap.yaml
- create scalardl overview dashboard
- create scalardl audit overview dashboard
- Change File path (files → files/grafana)
- Add and fix missing manifest for metrics.
- refactor grafana dashboard.json
> Add Scalar DL and Scalar DL Audit dashboard

- .github/workflows/helm_charts_scalar.yml
- .github/workflows/release.yml
- README.md
- Add `charts` to the documentation.
- Add badge for CI
> Modify README.md

- charts/scalardb/Chart.yaml
- charts/scalardb/README.md
- charts/scalardb/values.yaml
* scalardb application version (3.2.0 → 3.3.0)
> Bump up the scalar db version

- charts/scalardl-audit/Chart.yaml
- charts/scalardl-audit/README.md
- charts/scalardl-audit/values.yaml
- charts/scalardl/Chart.yaml
- charts/scalardl/README.md
- charts/scalardl/values.yaml
- Update Scalar DL and Scalar DL Audit app version
> Bump up Scalar DL and Scalar DL Audit

- charts/schema-loading/templates/batchjob-schema-loading.yaml
* Contact Port (-P) moved to Cassandra (Parameter applicable only for C*)
> Move contact port to Cassandra 

- charts/schema-loading/templates/batchjob-schema-loading.yaml
* JDBC support in schema-loading helm chart
> Add JDBC support in schema-loading helm chart

- .github/workflows/release.yml
- Created a mechanism to update path version to Minor version.
* Create a branch from the tag of the original minor version to be updated.
ex: scalardl-3.2.1 to scalardl-3.2.2
```
git checkout -b prepare-release-v3.2.2  refs/tags/scalardl-3.2.1
```
* Update Chart.yaml and values.yaml and execute `./scripts/update-chart-docs.sh`
* Chart.yaml
```
version: 3.2.2
appVersion: 3.2.2
```
* values.yaml
```
version: 3.2.2
```
* `git push`
> Modify release workflow for github actions

- charts/scalardb/values.schema.json
- I fixed CI for `verify-values-schema-json` was down
- https://github.com/scalar-labs/helm-charts/runs/4617917870?check_suite_focus=true
> Fix CI for `verify-values-schema-json`

- charts/scalardb/Chart.yaml
- charts/scalardb/README.md
- charts/scalardl-audit/Chart.yaml
- charts/scalardl-audit/README.md
- charts/scalardl/Chart.yaml
- charts/scalardl/README.md
- charts/schema-loading/Chart.yaml
- charts/schema-loading/README.md
-  Bumpup scalardl, scalardl-audit, scalardb, schema-loading minor version
* Modify scalar db grafana dashboard ( #61 )
* Add values.schema.json and verify values.schema.json ( #62 )
* Fixed the items pointed out in the security audit in scalardb charts ( #65 )
* remove -u for cosmos db ( #67 )
* https://github.com/scalar-labs/helm-charts/compare/8548276654abc04229b85dec0b5049e127208a96...main
> Bumpup scalardl, scalardl-audit, scalardb, schema-loading minor version

- .git-hooks/pre-commit
- README.md
- Added `pre-commit hook` to check if `README.md` and `values.schema.json` for each `helm-charts` are generated automatically.
> Add pre-commit hook for helm charts

- .github/workflows/release.yml
- docs/README.md
- docs/ReleaseFlow.md
* Add documentation describing the release flow.
> Add documents for release flow

- docs/conf/scalar-loki-stack-custom-values.yaml
Sorry, it's very minor.
This PR fixes the `POD`.
(It's not an abbreviation)
> Fix the incorrect spelled POD

- charts/scalar-manager/.helmignore
- charts/scalar-manager/Chart.yaml
- charts/scalar-manager/README.md
- charts/scalar-manager/README.md.gotmpl
- charts/scalar-manager/templates/_helpers.tpl
- charts/scalar-manager/templates/deployment.yaml
- charts/scalar-manager/templates/role.yaml
- charts/scalar-manager/templates/rolebinding.yaml
- charts/scalar-manager/templates/service.yaml
- charts/scalar-manager/templates/serviceaccount.yaml
- charts/scalar-manager/values.schema.json
- charts/scalar-manager/values.yaml
- docs/conf/scalar-manager-custom-values.yaml
- docs/getting-started-scalar-helm-charts.md
- docs/getting-started-scalar-manager.md
This PR creates a new Helm Chart for Scalar Manager.
> Create a new Helm Chart for Scalar Manager

- docs/README.md
- docs/how-to-use-customized-configuration.md
This PR adds a document about how to use a customized properties files.
This document is related to the following new features.
https://github.com/scalar-labs/helm-charts/pull/96
https://github.com/scalar-labs/helm-charts/pull/102
https://github.com/scalar-labs/helm-charts/pull/103
> Add doc how to use customized porperties file

- docs/README.md
- docs/configure-custom-values-envoy.md
- docs/configure-custom-values-file.md
- docs/configure-custom-values-scalar-manager.md
- docs/configure-custom-values-scalardb-graphql.md
- docs/configure-custom-values-scalardb.md
- docs/configure-custom-values-scalardl-auditor.md
- docs/configure-custom-values-scalardl-ledger.md
- docs/configure-custom-values-scalardl-schema-loader.md
- docs/mount-key-and-cert-for-scalardl.md
- docs/use-secret-for-credentilas.md
As part of re-organizing the document of [scalar-kubernetes](https://github.com/scalar-labs/scalar-kubernetes), I added/updated the document of Scalar Helm Charts.
This PR adds new documents `Configure a custom values file for Scalar Helm Chart`.
These documents do not cover all parameters since there are some parameters that users don't need to configure.
These documents describe `Required configurations` and `Optional configurations` from the perspective of users.
* Configure a custom values file for Scalar Helm Chart (root document)
* Configure a custom values file for Envoy
* Configure a custom values file for ScalarDB Server
* Configure a custom values file for ScalarDB GraphQL
* Configure a custom values file for ScalarDL Ledger
* Configure a custom values file for ScalarDL Auditor …
> Add docs how to create a custom values file

- README.md
- docs/conf/scalar-loki-stack-custom-values.yaml
- docs/how-to-use-customized-configuration.md
- docs/samples/scalardb/scalardb-multi-storage-sample/README.md
- docs/samples/scalardl/scalardl-auditor-mode-sample/README.md
This PR updates product names in each document.
* `Scalar DB` -> `ScalarDB`
* `Scalar DL` -> `ScalarDL`
Note: In each chart file, there are some old names. I will update them in another PR.
> Update product name in documents

- charts/scalardl/Chart.yaml
- charts/scalardl/README.md
- charts/scalardl/files/grafana/scalardl_grafana_dashboard.json
- charts/scalardl/files/grafana/scalardl_response_grafana_dashboard.json
- charts/scalardl/templates/ledger/configmap.yaml
This PR updates the product name from `Scalar DL` to `ScalarDL` in the ScalarDL Ledger chart directory.
> Update product name in ScalarDL Ledger chart

- charts/schema-loading/Chart.yaml
- charts/schema-loading/README.md
This PR updates the product name from `Scalar DL` to `ScalarDL` in the ScalarDL Schema Loader chart directory.
> Update product name in ScalarDL Schema Loader chart

- charts/scalardb-cluster/templates/scalardb-cluster/deployment.yaml
- charts/scalardb-cluster/values.yaml
This PR adjusts minor things in the ScalarDB Cluster chart for ready for 1.0.0 release.
> Improve minor things in ScalarDB Cluster chart

- charts/scalardb/Chart.yaml
> Update maintainers (ScalarDB)

- charts/scalardb-graphql/Chart.yaml
> Update maintainers (ScalarDB GraphQL)

- charts/scalardl/Chart.yaml
> Update maintainers (ScalarDL Ledger)

- charts/scalardl-audit/Chart.yaml
> Update maintainers (ScalarDL Auditor)

- charts/schema-loading/Chart.yaml
> Update maintainers (Schema Loader)

- charts/scalar-manager/Chart.yaml
@supl 
I added you to the maintainers of Scalar Manager chart.
> Update Chart.yaml (Scalar Manager)

- charts/scalardb-cluster/values.yaml
This PR sets default values (empty values) in the properties file.
These updates are related to the following PR.
https://github.com/scalar-labs/scalardb-cluster/pull/72
I updated the default values of the properties file based on the latest ScalarDB Cluster's properties file.
> Set empty value by default in properties file

- docs/configure-custom-values-envoy.md
- docs/configure-custom-values-file.md
- docs/configure-custom-values-scalar-manager.md
- docs/configure-custom-values-scalardb-cluster.md
- docs/configure-custom-values-scalardb-graphql.md
- docs/configure-custom-values-scalardb.md
- docs/configure-custom-values-scalardl-auditor.md
- docs/configure-custom-values-scalardl-ledger.md
- docs/configure-custom-values-scalardl-schema-loader.md
- docs/getting-started-scalar-helm-charts.md
- docs/getting-started-scalardb.md
- docs/how-to-deploy-scalar-products.md
- docs/how-to-deploy-scalardb-graphql.md
- docs/how-to-deploy-scalardb.md
We updated our recommendations for production environment. So, I updated some documents based on the new recommendations.
This updates based on the [Production checklist for ScalarDB Cluster](https://github.com/scalar-labs/scalar-kubernetes/blob/master/docs/ProductionChecklistForScalarDBCluster.md).
**Note:**
The above document is ScalarDB Cluster's one. However, the main updates of recommendation are related to the Kubernetes cluster things. So, I updated the Kubernetes cluster's recommendations based on the above `Production checklist for ScalarDB Cluster`.
Also, this PR includes other discussion results. I will add some comments about update later.
The updates in this PR related to the following PR in `scalar-kubernetes` repository. …
> Update recommendations in the documents

- docs/configure-custom-values-scalar-admin-for-kubernetes.md
This PR revises the document of using scalar-admin-for-kubernetes Helm Chart. I guess we forgot to revise this part when we change the custom values template in https://github.com/scalar-labs/helm-charts/pull/246#discussion_r1419993371.
https://github.com/scalar-labs/helm-charts/pull/246#discussion_r1419993371
- revised `configure-custom-values-scalar-admin-for-kubernetes.md`
> Revise the document of scalar-admin-for-kubernetes

- .github/workflows/helm_charts_scalar.yml
This PR updates the Kubernetes versions in the CI.
After we run the CI and merge this PR to the `main` branch, I will update the `README.md` to list the supported Kubernetes versions.
N/A
- Update the Kubernetes version in the CI.
I checked the supported version of each managed Kubernetes and updated the versions based on them.
- https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#available-versions
- https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar
- https://cloud.google.com/kubernetes-engine/docs/release-notes#current_versions
- https://docs.oracle.com/en-us/iaas/Content/ContEng/Concepts/contengaboutk8sversions.htm
N/A
> Update Kubernetes versions in CI

- README.md
This PR updates the supported Kubernetes versions in `README.md`.
We updated the Kubernetes versions in the CI in #270. And, all the tests passed in new versions.
So, I updated the supported version information in README based on the above new CI.
- #270
- Update supported Kubernetes versions.
N/A
N/A
> Update supported Kubernetes versions in README

- charts/scalardl-ledger-monitoring/Chart.yaml
- charts/scalardl-ledger-monitoring/README.md
This PR fixes the metadata (`description` field) in the `Chart.yaml` file.
N/A
- Fix `description`.
N/A
N/A
> [scalardl-ledger-monitoring] Fix metadata in Chart.yaml
